#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

[[ -d ./D1 ]] && rm -rf ./D1
[[ -d ./"The Covenant (2023) [1080p] [WEBRip] [5.1] [YTS.MX]" ]] && rm -rf ./"The Covenant (2023) [1080p] [WEBRip] [5.1] [YTS.MX]"
mkdir ./"The Covenant (2023) [1080p] [WEBRip] [5.1] [YTS.MX]"
mkdir ./"The Covenant (2023) [1080p] [WEBRip] [5.1] [YTS.MX]/Subs"
touch ./"The Covenant (2023) [1080p] [WEBRip] [5.1] [YTS.MX]/The Covenant (2023) [1080p].mkv"
touch ./"The Covenant (2023) [1080p] [WEBRip] [5.1] [YTS.MX]/Subs/The Covenant (2023) [1080p].srt"
touch ./"The Covenant (2023) [1080p] [WEBRip] [5.1] [YTS.MX]/www.YTS.MX.jpg"
touch ./"The Covenant (2023) [1080p] [WEBRip] [5.1] [YTS.MX]/YTSProxies.com.txt"
