#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"


# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

coord_center () {
	local AREA=${1} # Available space width or height
	local OBJ=${2} # Object width or height
	local CTR
	local REM
	local AC
	local OC
	local COORD

	[[ ${_DEBUG} -ge ${_HIGH_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"

	echo "AREA:${AREA}" >&2
	echo "OBJ:${OBJ}" >&2

	CTR=$(( AREA / 2 ))
	REM=$(( CTR % 2 ))
	[[ ${REM} -ne 0 ]] && AC=$(( CTR + 1 )) || AC=${CTR}
	echo "CTR:${CTR}, REM:${REM}, AC:${AC}" >&2

	CTR=$(( OBJ / 2 ))
	REM=$(( CTR % 2 ))
	[[ ${REM} -ne 0 ]] && OC=$(( CTR + 1 )) || OC=${CTR}
	echo "CTR:${CTR}, REM:${REM}, OC:${OC}" >&2

	COORD=$(( AC - OC ))
	echo "COORD:${COORD}" >&2

	echo ${COORD}
}

W=20
H=20

clear
cursor_off
echo "_MAX_COLS:${_MAX_COLS}"
echo "_MAX_ROWS:${_MAX_ROWS}"

L=$(coord_center ${_MAX_COLS} ${W})
T=$(coord_center ${_MAX_ROWS} ${W})

msg_unicode_box 0 ${L} ${W} ${H}
tcup 1 $((L+2));echo -n "Centered Width"
read
clear
msg_unicode_box ${T} ${L} ${W} ${H}
tcup $((T+1)) $((L+2));echo -n "Centered Height"
read
clear
cursor_on
