#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/STR.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

typeset -a DIR_LIST=()
typeset -a LOG_LIST=()
typeset -a DIR_INODES=()
typeset -a LOG_INODES=()
typeset -a DIR_NOT_LOG=()
typeset -a LOG_NOT_DIR=()

_DOWNLOAD_DIR=~/Downloads/Torrents/Library/web
_YTS_DIR=~/.local/share/yts
_LOG=yts.downloads
_DOWNLOAD_LOG=${_YTS_DIR}/${_LOG}
_NEW_LOG=/tmp/_LOG.new

# Execution
clear

DIR_LIST=("${(f)$(ls -Ai ${_DOWNLOAD_DIR})}")

for L in ${(on)DIR_LIST};do
	DIR_INODE=$(cut -d' ' -f1 <<<${L})
	[[ ${DIR_FN:e} == 'part' ]] && continue
	DIR_INODES+=${DIR_INODE}
done

while read LINE;do
	LOG_INODE=$(cut -d'|' -f1 <<<${LINE})
	LOG_INODES+=${LOG_INODE}
done < ${_DOWNLOAD_LOG}

echo "Download Directory:${WHITE_FG}${_DOWNLOAD_DIR}${RESET}"
echo "Download Log:${WHITE_FG}${_DOWNLOAD_LOG}${RESET}"
echo

NDX=0
echo "Download Directory contains:${WHITE_FG}${#DIR_INODES}${RESET} $(str_pluralize inode ${#DIR_INODES})"
for L in ${DIR_INODES};do
	((NDX++))
	[[ ${LOG_INODES[(i)${L}]} -le ${#LOG_INODES} ]] || DIR_NOT_LOG+=${L}
	printf "${WHITE_FG}%d${RESET}) %s\n" ${NDX} ${L}
done
echo

NDX=0
echo "Download Log contains:${WHITE_FG}${#LOG_INODES}${RESET} $(str_pluralize inode ${#LOG_INODES})"
for L in ${LOG_INODES};do
	((NDX++))
	[[ ${DIR_INODES[(i)${L}]} -le ${#DIR_INODES} ]] || LOG_NOT_DIR+=${L}
	printf "${WHITE_FG}%d${RESET}) %s\n" ${NDX} ${L}
done

typeset -a DIR_ROWS=()
if [[ -n ${DIR_NOT_LOG} ]];then
	for L in ${DIR_NOT_LOG};do
		DIR_ROWS+="${L}|${$(find ${_DOWNLOAD_DIR} -inum ${L}):t}"
	done
fi

typeset -a LOG_ROWS=()
if [[ -n ${LOG_NOT_DIR} ]];then
	for L in ${LOG_NOT_DIR};do
		LOG_ROWS+=$(grep ${L} ${_DOWNLOAD_LOG})
	done
fi

echo
if [[ ${#DIR_NOT_LOG} -ne 0 ]];then
	echo "Download Directory contains ${WHITE_FG}${#DIR_NOT_LOG}${RESET} $(str_pluralize inode ${#DIR_NOT_LOG}) ${ITALIC}${RED_FG}not${RESET} in log"
	NDX=0
	for L in ${DIR_ROWS};do
		((NDX++))
		printf "${WHITE_FG}%d${RESET}) %s\n" ${NDX} ${L[1,80]}
	done
	echo
	echo "DIR CHECK ${RED_FG}FAILED${RESET} -> Add missing files to log"
else
	echo "DIR CHECK ${GREEN_FG}OK${RESET} -> Directory entries match log contents"
fi
echo

if [[ ${#LOG_NOT_DIR} -ne 0 ]];then
	echo "Download Log contains ${WHITE_FG}${#LOG_NOT_DIR}${RESET} $(str_pluralize inode ${#LOG_NOT_DIR}) ${ITALIC}${RED_FG}not${RESET} in directory"
	NDX=0
	for L in ${LOG_ROWS};do
		((NDX++))
		printf "${WHITE_FG}%d${RESET}) %s\n" ${NDX} ${L[1,80]}
	done
	echo
	echo "LOG CHECK ${RED_FG}FAILED${RESET} -> Remove missing files from log"
else
	echo "LOG CHECK ${GREEN_FG}OK${RESET} -> Log entries match directory contents"
fi
