#!/usr/bin/zsh
# TODO: Strip audio fix code - unnecessary
GET_AV=false
[[ ${1} == '-A' ]] && GET_AV=true && shift

typeset -a AUDIO=()
typeset -a VIDEO=()
typeset -a LIST=()

_YTS_URL_LOG=~/.local/share/yts/yts.url.log
_DOWNLOAD_DIR=~/Downloads/Torrents/Library/web

last_file_downloaded () {
	local ST=''
	local FN=''
	local IN=''

	ST=$(stat -c"%W|%i|%n" ${_DOWNLOAD_DIR}/* | sort -t'|' -k1 -r | head -1) # Sort by birth date; grab most recent
	FN=$(cut -d'|' -f3 <<<${ST}) # Filename
	IN=$(cut -d'|' -f2 <<<${ST}) # Inode

	if [[ -e ${FN} ]];then
		echo "${FN}|${IN}"
		return 0
	else
		return 1
	fi
}

if [[ ${GET_AV} == 'true' ]];then
	LIST=("${(f)$(
		while read LINE;do
			echo ${LINE}
		done<<<$("${PYTHON:-python3}" -Werror -Xdev "$(dirname "$(realpath "$0")")/yt_dlp/__main__.py" -F "$@")
	)}")

	for L in ${LIST};do
		[[ ${L:l} =~ 'audio' && ${L:l} =~ 'https' ]] && AUDIO+=$(tr -s '[:space:]' <<<${L} | sed 's/ /|/g' | tr -s '|' | sed 's/,//g')
		[[ ${L:l} =~ 'video' && ${L:l} =~ 'https' ]] && VIDEO+=$(tr -s '[:space:]' <<<${L} | sed 's/ /|/g' | tr -s '|' | sed 's/,//g')
	done

	AUDIO_CODE=$(
	for A in ${AUDIO};do
		[[ ${A} =~ 'drc' ]] && continue
		echo "$(cut -d'|' -f12 <<<${A})|$(cut -d'|' -f1 <<<${A})"
	done | sort -nr | head -1 | cut -d'|' -f2
	)

	VIDEO_CODE=$(
	for V in ${VIDEO};do
		echo "$(cut -d'|' -f12 <<<${V})|$(cut -d'|' -f1 <<<${V})"
	done | sort -nr | head -1 | cut -d'|' -f2
	)

	AV_CODES="${VIDEO_CODE}+${AUDIO_CODE}"
	echo "AV_CODES:${AV_CODES}"
	/usr/local/bin/yt-dlp -f ${AV_CODES} -Rinfinite "$@"
else
	/usr/local/bin/yt-dlp -Rinfinite "$@"
fi

FN=$(last_file_downloaded | cut -d'|' -f1)
[[ -e ${FN} ]] && fsub -y -Y ${FN} || echo "No file for:${@}" >> ${_YTS_URL_LOG}

echo "yt download:${@}" >> ${_YTS_URL_LOG}
