#!/usr/bin/zsh
#vim: syntax off
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

typeset -A CLMN_OPTS

CLMN_OPTS[EXE]="/usr/bin/clementine"

while true;do
	read -s -k1 KEY
	case ${KEY} in
		q) break;;
		n) $(${CLMN_OPTS[EXE]} -f >/dev/null 2>&1);;
		p) $(${CLMN_OPTS[EXE]} -r >/dev/null 2>&1);;
		t) $(${CLMN_OPTS[EXE]} -t >/dev/null 2>&1);;
		V) $(${CLMN_OPTS[EXE]} --volume-up >/dev/null 2>&1);;
		v) $(${CLMN_OPTS[EXE]} --volume-down >/dev/null 2>&1);;
		s) $(${CLMN_OPTS[EXE]} --seek-by 10 >/dev/null 2>&1);;
	esac
done

#      -p           --play
#                 Start the playlist currently playing.
#
#       -t           --play-pause
#                 Play if stopped, pause if playing.
#
#       -u           --pause
#                 Pause playback
#
#       -s           --stop
#                 Stop playback
#
#       -q           --stop-after-current
#                 Stop playback after current track
#
#       -r           --previous
#                 Skip backwards in playlist.
#
#       -f           --next
#                 Skip forwards in playlist.
#
#       -v           --volume <value>
#                 Set the volume to <value> percent.
#
#                 --volume-up
#                 Increase the volume by 4%.
#
#                 --volume-down
#                 Decrease the volume by 4%..
#
#                 --seek-to <seconds>
#                 Seek the currently playing track to an absolute position.
#
#                 --seek-by <seconds>
#                 Seek the currently playing track by a relative amount.


