#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLINK="\033[5m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

if [[ ${1} == 'in' ]];then
	cp LIB_INIT.zsh /usr/local/lib
	cp LIB_DEPS.zsh /usr/local/lib
else
	cp LIB_INIT.prod /usr/local/lib/LIB_INIT.zsh
	cp LIB_DEPS.prod /usr/local/lib/LIB_DEPS.zsh
fi
