#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

_SCRIPT="${WHITE_FG}${0:t}${RESET}"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

CYCLE=1
NDX_1=0
NDX_2=0
C_NDX_1=1
C_NDX_2=2
OFFSET=1

C_OBJ="\\u2622"
L_OBJ="\\u23FA"
typeset -a COLORS=("\033[1;31m" "\033[1;32m" "\033[1;33m" "\033[1;35m" "\033[1;36m" "\033[1;37m")

cursor_off
while true;do
	clear
	xrandr --output eDP-1 --brightness 1
	[[ ${NDX_1} -ge $(( (_MAX_ROWS / 2) )) ]] && NDX_1=0
	[[ ${NDX_2} -ge $(( (_MAX_COLS / 2) - ${#_SCRIPT} )) ]] && NDX_2=0
	[[ ${C_NDX_1} -gt 6 ]] && C_NDX_1=1
	[[ ${C_NDX_2} -gt 6 ]] && C_NDX_2=1
	if [[ ${CYCLE} -eq 2 ]];then
		((NDX_1+=4))
		((NDX_2+=15))
		tcup ${NDX_1} ${NDX_2}; echo -n ${COLORS[${C_NDX_1}]}${L_OBJ}${RESET}
		tcup ${NDX_1} $(( _MAX_COLS - NDX_2 )); echo -n ${COLORS[${C_NDX_1}]}${L_OBJ}${RESET}
		tcup $(( _MAX_ROWS - NDX_1 )) $(( _MAX_COLS - NDX_2 )); echo -n ${COLORS[${C_NDX_1}]}${L_OBJ}${RESET}
		tcup $(( _MAX_ROWS - NDX_1 )) $(( NDX_2 )); echo -n ${COLORS[${C_NDX_1}]}${L_OBJ}${RESET}
		CYCLE=1
		((C_NDX_1++))
	else
		tcup 0 0; echo -n ${COLORS[${C_NDX_2}]}${C_OBJ}${RESET}
		tcup 0 $(( _MAX_COLS - OFFSET )); echo -n ${COLORS[${C_NDX_2}]}${C_OBJ}${RESET}
		tcup ${_MAX_ROWS} $(( _MAX_COLS - OFFSET )); echo -n ${COLORS[${C_NDX_2}]}${C_OBJ}${RESET}
		tcup ${_MAX_ROWS} 0; echo -n ${COLORS[${C_NDX_2}]}${C_OBJ}${RESET}
		CYCLE=2
		((C_NDX_2++))
	fi
	read -s -t2 -k1 KEY
	[[ ${?} -ne 1 ]] && break
	xrandr --output eDP-1 --brightness 0
	sleep .5
done
cursor_on
xrandr --output eDP-1 --brightness 1
clear
