#!/usr/bin/zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"
BOLD="\033[1m"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

tabs 6
read -r -d '' DESC<<EOF
Compile C lang source file
\tVery basic compilation
EOF

usage () {
	PENDING_MSGS=${1}

	echo "${WHITE_FG}Usage${RESET}:${0} <C_SOURCE>"
	echo "${WHITE_FG} Desc${RESET}:${DESC}"

	exit_leave $(err_msg_exit ${PENDING_MSGS})
}

# Execution
FN_ARG=''
if [[ ${1} == '-H' ]];then
	usage
fi

if [[ ${#} -eq 0 ]];then
	usage
else
	FN_ARG=${1}
	[[ ! ${FN_ARG:e} == 'c' ]] && usage "Invalid file type:${FN_ARG:e}"
fi

C_SOURCE=${FN_ARG}
C_EXE=${C_SOURCE:t:r}

echo " Compiling:${WHITE_FG}${C_SOURCE}${RESET}"
echo "Executable:${WHITE_FG}${C_EXE}${RESET}"

[[ -e a.out ]] && /bim/rm -f a.out
gcc ${C_SOURCE}

if [[ -e a.out ]];then
	mv a.out ${C_EXE}
	echo "   Created:${WHITE_FG}${C_EXE}${RESET} from ${C_SOURCE}"
else
	exit_leave $(err_msg_exit "Problem compiling:${C_SOURCE}")
fi

exit_leave
