#!/usr/bin/zsh
 
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

_SCRIPT=${0:t}

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

usage () {
	local PENDING_MSGS=${1}
	echo "${WHITE_FG}Usage${RESET}: ${_SCRIPT} on|off|toggle"
	echo " ${WHITE_FG}Desc${RESET}: enable,disable, or toggle the dock"

	exit_leave $(err_msg_exit ${PENDING_MSGS})
}

toggle () {
	gnome-extensions disable ubuntu-dock@ubuntu.com
	gnome-extensions enable ubuntu-dock@ubuntu.com
}

# Execution
[[ ${1} == "-H" ]] && usage

ACTION=${1:=toggle}

case ${ACTION} in
	on) gnome-extensions enable ubuntu-dock@ubuntu.com;;
	off) gnome-extensions disable ubuntu-dock@ubuntu.com;;
	toggle) gnome-extensions disable ubuntu-dock@ubuntu.com;gnome-extensions enable ubuntu-dock@ubuntu.com;;
	*) usage "Invalid action:${ACTION}";;
esac
