#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"


# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/SELECT.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

_WEB_ROOT="https://python-gtk-3-tutorial.readthedocs.io/en/latest"
_SCRIPT=${0:t}

LIST=("${(f)$(wget -qO- 'https://python-gtk-3-tutorial.readthedocs.io/en/latest/index.html' | pup 'a attr{href}' | grep -v '#\|http\|_' | sort -u)}")


while true;do
	clear # wipe screen
	sel_set_list $(for L in ${LIST};do echo ${L:r};done)
	sel_list -S -O ${CYAN_FG} -F"<w>Select GObject or <h>(q)uit<N>" -H"Online Docs"
	clear # wipe screen
	eval "/usr/bin/firefox ${_WEB_ROOT}/${_SEL_VAL}.html 2>/dev/null &"
done
