#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"


# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

_ARG="<SEARCHTERM>"

usage () {
	local PENDING_MSGS=${1}

	echo "\nUsage: ${_SCRIPT} ${_ARG}"

	exit_leave $(err_msg_exit ${PENDING_MSGS})
}

[[ ${1} == '-H' ]] && usage
[[ ${#} -eq 0 ]] && usage "Missing argument:${_ARG}"

ITEMS=7

tput smcup
ddgr --url-handler=/usr/local/bin/system/launchers/run_google-chrome --num ${ITEMS} ${@} 2>/dev/null
tput rmcup

exit_leave

