#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"


# Imports
_LIB_DIR=/usr/local/lib
source ${_LIB_DIR}/LIB_INIT.zsh
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/MSG.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

imdb () {
	local STR=${@}
	local URL

	msg_box "Querying imdb..."

	STR=$(sed 's/ /%20/g' <<<${STR})

	{
	URL=$(wget --quiet -O - "http://www.imdb.com/find?q=${STR}" | pup 'div' .ipc-metadata-list-summary-item__t attr{href} | grep 'ttl_1' | sed 's#/?ref.*##')
	URL="http://www.imdb.com${URL}"
	if [[ ! $(curl --connect-timeout 2 -Is "${URL}" | head -1) =~ "404" ]];then
		nohup google-chrome "${URL}" >/dev/null &
	else
		msg_box -p -PK "${0}: Could not obtain a valid URL:${URL}"
	fi
	} 2>/dev/null
}

do_smcup

imdb ${@}

exit_leave

