#!/usr/bin/zsh
# Vim: syntax off
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh
_DEPS+=(LIST.zsh SELECT.zsh)
source ${_LIB_DIR}/LIB_DEPS.zsh

# Declarations
typeset -A _ACTIVE=()
typeset -A _DESC=()
typeset -A _LOAD=()
typeset -A _SORT_TABLE=()
typeset -A _SUB=()
typeset -A _UNIT=()
typeset -a _LOCAL_LIST=()

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

read -r -d '' DESC<<EOF
View/manage systemd unit files
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTR
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTR+="-${OPTS[${O}]}"
	done
	echo ${OPTSTR}
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		t) echo "<FILE_TYPE>";;
		s) echo "<SEARCH_TERM>";;
	esac
}

usage () {
	local OPTS=$(parse_opts ${OPTSTR})
	local -a PENDING_MSGS=(${@})

	[[ ${_SMCUP} == 'true' ]] && do_rmcup
	tabs 5

	(
	echo -e "${WHITE_FG}Usage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} $(opt_type s) \n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-R${RESET} daemon-reload"
	echo -e "${WHITE_FG}-a${RESET} show only alias unit files"
	echo -e "${WHITE_FG}-d${RESET} show only disabled unit files"
	echo -e "${WHITE_FG}-e${RESET} show only enabled unit files"
	echo -e "${WHITE_FG}-g${RESET} show only generated unit files"
	echo -e "${WHITE_FG}-i${RESET} show only indirect unit files"
	echo -e "${WHITE_FG}-m${RESET} show only masked unit files"
	echo -e "${WHITE_FG}-r${RESET} show only running services"
	echo -e "${WHITE_FG}-s${RESET} show only static unit files"
	echo -e "${WHITE_FG}-t${RESET} show only transient unit files"
	echo -e "${WHITE_FG}\nDesc${RESET}:${DESC}"
	) >&2

	exit_leave $(err_msg_exit ${PENDING_MSGS})
}

OPTSTR=":HDRadegimrst"
OPTIND=0
RUNNING=false

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     R) sudo systemctl daemon-reload;;
	  a|d|e|g|i|m|s|t) _STATE_SELECT+=${_STATE_TABLE[${OPTION}]};;
	  r) RUNNING=true;;
     :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: ${BOLD}${RED_FG}Unknown option${RESET} -${OPTARG}"; usage;;
	esac
done
shift $(( OPTIND - 1 ))
#--End GetOpts--

# Execution
[[ ${_DEBUG} -eq 0 ]] && do_smcup

NDX=0
while read -r LINE; do # Read systemctl output LINE-by-LINE using Zsh's = modifier (word splitting)
  LINE=${LINE//[^$'\x00'-$'\x7f']} # Scrub non ascii
  LINE=$(printf '%b' "${LINE}") # Convert any hex
  FIELDS=( ${=LINE} ) # Split LINE into 5 FIELDS (handles trailing multi-word descriptions cleanly)

  [[ -z ${FIELDS[1]} ]] && continue
  [[ ${FIELDS[4]} =~ 'mounted|plugged' ]] && continue

  ((NDX++))
  if (( ${#FIELDS} >= 5 )); then
    _UNIT[${NDX}]="${FIELDS[1]}"
    _LOAD[${NDX}]="${FIELDS[2]}"
    _ACTIVE[${NDX}]="${FIELDS[3]}"
    _SUB[${NDX}]="${FIELDS[4]}"
    _DESC[${NDX}]="${FIELDS[5,-1]}"
  fi
  _LOCAL_LIST+=${NDX}
done < <(systemctl list-units --no-legend --no-pager)

_SORT_TABLE=(1 _DESC 2 _SUB 3 _UNIT)
#for K in ${(k)_SORT_TABLE};do
#	printf "KEY:%s VAL:%s\n" ${K} ${_SORT_TABLE[${K}]}
#	echo ${(k)_SORT_TABLE[(r)${_SORT_TABLE[${K}]}]}
#done

list_set_header 'printf "%-70s %10s %-60s" "Description" "State" "Unit File"'

# Set line item
list_set_line_item ' 
local SNDX=${_SORT_NDX[${_LIST_NDX}]}
printf "${BOLD}${WHITE_FG}%4s${RESET}) ${SHADE}${BAR}%-70s %10s %-50s${RESET}" ${_LIST_NDX} ${${_DESC[${SNDX}]}[1,70]} ${_SUB[${SNDX}]} ${${_UNIT[${SNDX}]}[1,60]}
'

list_set_prompt_msg '
printf "Press ${WHITE_FG}Home End PgUp PgDn, <${GREEN_FG}Enter${RESET}>${RESET} or <${WHITE_FG}q${RESET}>uit${RESET}"
'

list_add_header_break 6
list_set_select_action "manage unit file"
list_set_reuse_stale true
list_set_barlines true
list_set_position_hold true
list_set_sortable true
list_set_sort_index '_DESC'
list_set_selectable false

while true;do
	# Get selection
	list_select ${_LOCAL_LIST}
	[[ ${?} -eq 0 ]] && break

	# Get selections
	_MARKED=($(list_get_selected))

	if [[ $(list_get_selected_count) -ne 0 ]];then
		action_do
	fi
done

exit_leave
