#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

# Imports
_LIB_DIR=${ZSH_LIB_DIR:=/usr/local/lib}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/VALIDATE.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

# Execution
[[ ${#} -eq 0 ]] && exit_leave $(msg_exit E "Missing argument:<FORMULA>")

if [[ ${1} == '-H' ]];then
	tabs 5
	echo "\n${WHITE_FG}Usage${RESET}:${0:t} [-H -p <INT>] '<FORMULA>'"
	echo "${WHITE_FG} Desc${RESET}:Execute mathematical formula\n"
	echo "Options: -p precision"
	return
fi

PRECISION=2
[[ ${1} == '-p' ]] && shift && PRECISION=${1} && shift
if ! validate_is_integer ${PRECISION};then
	exit_leave $(msg_exit E "PRECISION:${PRECISION} must be integer")
fi

FORMULA=${@}
	
echo "scale=${PRECISION}; ${FORMULA}" | bc 
