#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

# Imports
_LIB_DIR=${ZSH_LIB_DIR:=/usr/local/lib}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

usage () {
	echo "Usage:${_SCRIPT} [<FILE>]"
	echo " Desc:Paging for either <FILE> or <PIPE>"
	exit_leave
}

#Execution
if [[ -t 0 ]];then
	[[ ${1} == '-H' ]] && usage
	[[ ${#} -eq 0 ]] && exit_leave $(err_msg_exit E "Missing argument:<FN>") || FN=${1}
	[[ ! -e ${FN} ]] && exit_leave $(err_msg_exit E "File not found:${FN}")
fi

tput smcup
if [[ -t 0 ]];then
	less $1
else
	while read LINE;do
		echo ${LINE}
	done | less -R
fi
tput rmcup

exit_leave
