#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

# Constants
_REPO=~/Code/REPO
_USER_DIR=${_REPO}/USER_DIR
_ETC_SUPPORT=${_REPO}/ETC_SUPPORT
_PYTHON=${_REPO}/PYTHON
_SYSTEM=${_REPO}/SYSTEM
_DEV=${_REPO}/LOCAL
_VIM_CFG=${_REPO}/VIM_CFG
_VIM_CFG_USER=${_REPO}/VIM_CFG/USER
_ZSH_CFG=${_REPO}/ZSH_CFG
_ZSH_CFG_USER=${_REPO}/ZSH_CFG/USER
_ZSH_LIB_MODULES=${_REPO}/ZSH_LIB
_ZSH_LIB_UTILS=${_REPO}/ZSH_LIB_UTILS
_ZSH_NON_LIB_UTILS=${_REPO}/ZSH_NON_LIB_UTILS
_NON_ZSH_UTILS=${_REPO}/NON_ZSH_UTILS

_DEV_DIR=${HOME}/Code/LOCAL
_PYTHON_DIR=${HOME}/Code/LANG/Python/PROJECTS
_UL_BIN_DIR=/usr/local/bin
_UL_BIN_SYS_DIR=/usr/local/bin/system
_UL_BIN_CONV_DIR=/usr/local/bin/conversion
_UL_BIN_PY_DIR=/usr/local/bin/__pyscripts__
_UL_ETC_DIR=/usr/local/etc
_UL_LIB_DIR=/usr/local/lib
_VIM_DIR=${HOME}/.vim
_ZSH_DIR=${HOME}/.zsh
_ZSH_CFG_DIR=/etc/zsh

# Declarations
typeset -a _DEVELOPMENT=()
typeset -a _NON_ZSH=()
typeset -a _PYTHON_FILES=()
typeset -a _ULB=()
typeset -a _UL_ETC_FILES=()
typeset -a _UL_LIB_ZSH_FILES=()
typeset -a _USER_FILES=()
typeset -a _ZSH=()
typeset -a _ZSH_CFG_FILES=()
typeset -a _ZSH_LIB=()
typeset -a _ZSH_NON_LIB=()

# Functions
copy_dev_files () {
	typeset -A DEV_LIST

	/bin/rm -rf ${_DEV}/* >/dev/null 2>&1

	echo "${WHITE_FG}DEVELOPMENT${RESET}" >&2
	BIN_LIST=("${(f)$(find /usr/local/bin -type f ! -path /usr/local/bin)}")
	LIST=("${(f)$(find ~/Code/LOCAL -maxdepth 1 -type d)}")

	for L in ${LIST};do
		DEV_LIST[${L:t}]=1
	done

	for D in ${BIN_LIST};do
		[[ ${DEV_LIST[${D:t}]} -eq 1 ]] && cp -r ${_DEV_DIR}/${D:t} ${_DEV}
	done

	cp -r ${_DEV_DIR}/LIBS/scratch ${_DEV}
	cp -r ${_DEV_DIR}/spanish_quiz ${_DEV}
	cp -r ${_DEV_DIR}/takeout ${_DEV}
	cp -r ${_DEV_DIR}/manage_db ${_DEV}
}

copy_zsh_lib_utils () {
	echo "${WHITE_FG}ZSH LIB UTILS${RESET}" >&2
	for L in ${_ZSH_LIB};do
		cp "${L}" ${_ZSH_LIB_UTILS}
	done
}

copy_non_lib_utils () {
	echo "${WHITE_FG}ZSH NON LIB UTILS${RESET}" >&2
	for L in ${_ZSH_NON_LIB};do
		cp "${L}" ${_ZSH_NON_LIB_UTILS}
	done
}

copy_non_zsh_utils () {
	echo "${WHITE_FG}NON ZSH UTILS${RESET}" >&2
	for L in ${_NON_ZSH};do
		cp "${L}" ${_NON_ZSH_UTILS}
	done
}

copy_conv_files () {
	echo "${WHITE_FG}ULB CONVERSION FILES${RESET}" >&2
	rsync -a ${_UL_BIN_CONV_DIR} ${_ZSH_LIB_UTILS}
}

copy_py_files () {
	echo "${WHITE_FG}ULB PYTHON SCRIPT FILES${RESET}" >&2
	rsync -a ${_UL_BIN_PY_DIR} ${_ZSH_LIB_UTILS}
}

copy_zsh_libs () {
	echo "${WHITE_FG}ZSH LIBS${RESET}" >&2
	ZSH_LIBS=("${(f)$(find ${_UL_LIB_DIR} -maxdepth 1 -type f)}")
	for L in ${ZSH_LIBS};do
		cp "${L}" ${_ZSH_LIB_MODULES}
	done
}

copy_sys_files () {
	echo "${WHITE_FG}SYSTEM FILES${RESET}" >&2
	rsync -a --no-links ${_UL_BIN_SYS_DIR} ${_SYSTEM}
}

copy_etc_files () {
	echo "${WHITE_FG}ETC SUPPORT FILES${RESET}" >&2
	for L in ${_UL_ETC_FILES};do
		cp "${L}" ${_ETC_SUPPORT}
	done
}

copy_zsh_cfg_files () {
	echo "${WHITE_FG}ZSH CONFIG FILES${RESET}" >&2
	for L in ${_ZSH_CFG_FILES};do
		cp "${L}" ${_ZSH_CFG}
	done
	sudo rsync -a --no-links ${_ZSH_DIR} ${_ZSH_CFG_USER}
	cp ${HOME}/.zshrc ${_ZSH_CFG_USER}
	cp ${HOME}/.zsh_history ${_ZSH_CFG_USER}
}

copy_vim_cfg_files () {
	echo "${WHITE_FG}VIM CONFIG FILES${RESET}" >&2
	sudo rsync -a --no-links --exclude='undo' ${_VIM_DIR} ${_VIM_CFG}
	cp ~/.vimrc ${_VIM_CFG_USER}
}

copy_python_files () {
	echo "${WHITE_FG}PYTHON PROJECT FILES${RESET}" >&2
	rsync -a ${_PYTHON_DIR} ${_PYTHON}
	/bin/rm -f ${_PYTHON}/PROJECTS/ts/venv/.gitignore
	/bin/rm -f ${_PYTHON}/PROJECTS/ts/.idea/.gitignore
	/bin/rm -f ${_PYTHON}/PROJECTS/st/venv/.gitignore
	/bin/rm -f ${_PYTHON}/PROJECTS/st/.idea/.gitignore
}

copy_user_files () {
	echo "${WHITE_FG}USER FILES${RESET}" >&2
	cp -R ${HOME}/.mvq ${_USER_DIR} 2>/dev/null
	cp -R ${HOME}/.yts ${_USER_DIR} 2>/dev/null
	cp -R ${HOME}/.openvpn3 ${_USER_DIR} 2>/dev/null
	cp -R ${HOME}/Code/LOCAL/ovpn/ovpn ${_USER_DIR} 2>/dev/null
}

# Execution

pushd ~/Code

# Build tree
#[[ -e ${_REPO} ]] && /bin/rm -rf ${_REPO}
#[[ ! -e ${_REPO} ]] && mkdir -p ${_REPO}
[[ ! -e ${_USER_DIR} ]] && mkdir -p ${_USER_DIR}
[[ ! -e ${_DEV} ]] && mkdir -p ${_DEV}
[[ ! -e ${_ETC_SUPPORT} ]] && mkdir -p ${_ETC_SUPPORT}
[[ ! -e ${_PYTHON} ]] && mkdir -p ${_PYTHON}
[[ ! -e ${_SYSTEM} ]] && mkdir -p ${_SYSTEM}
[[ ! -e ${_VIM_CFG} ]] && mkdir -p ${_VIM_CFG}
[[ ! -e ${_VIM_CFG_USER} ]] && mkdir -p ${_VIM_CFG_USER}
[[ ! -e ${_ZSH_CFG} ]] && mkdir -p ${_ZSH_CFG}
[[ ! -e ${_ZSH_CFG_USER} ]] && mkdir -p ${_ZSH_CFG_USER}
[[ ! -e ${_ZSH_LIB_MODULES} ]] && mkdir -p ${_ZSH_LIB_MODULES}
[[ ! -e ${_ZSH_LIB_UTILS} ]] && mkdir -p ${_ZSH_LIB_UTILS}
[[ ! -e ${_ZSH_NON_LIB_UTILS} ]] && mkdir -p ${_ZSH_NON_LIB_UTILS}
[[ ! -e ${_NON_ZSH_UTILS} ]] && mkdir -p ${_NON_ZSH_UTILS}

# Readme
cp ./README.md ${_REPO}

# Updater
cp ./do_commit ${_REPO}

# Organize /usr/local/bin
_ULB=("${(f)$(file $(find ${_UL_BIN_DIR} -maxdepth 1 -type f))}")

for L in ${_ULB};do
	FN=$(cut -d: -f1 <<<${L})
	SIG=$(cut -d: -f2- <<<${L})
	[[ ${SIG} =~ 'zsh' ]] && _ZSH+=${FN} || _NON_ZSH+=${FN}
done

# zsh scripts  
for L in ${_ZSH};do
	if grep -q "ZSH_LIB_DIR" ${L};then
		# zsh lib utils
		_ZSH_LIB+=${L}
	else
		# zsh non lib utils
		_ZSH_NON_LIB+=${L}
	fi
done

LIST=("${(f)$(find ${_UL_LIB_DIR} -maxdepth 1 -type f)}")
for L in ${LIST};do
	[[ $(file ${L}) =~ 'zsh' ]] && _UL_LIB_ZSH_FILES+=${L} || continue
done

echo "Total lib utils:${#_ZSH_LIB}"
echo "Total non lib utils:${#_NON_ZSH}"
echo "Total non zsh utils:${#_ZSH_NON_LIB}"
echo "Total library files:${#_UL_LIB_ZSH_FILES}"

# Copy /usr/local/bin
copy_zsh_lib_utils
copy_non_lib_utils
copy_non_zsh_utils
copy_zsh_libs
copy_conv_files # Copy /usr/local/bin/conversion
copy_py_files # Copy /usr/local/bin/__pyscripts__

# system
copy_sys_files # Copy /usr/local/bin/system
copy_user_files # Copy ${HOME}

# dev
copy_dev_files
echo "Total development directories:$(find ${_DEV} -maxdepth 1 -type d | wc -l)"
echo "Total development files:$(find ${_DEV} -type f | wc -l)"

# etc
_UL_ETC_FILES=("${(f)$(find ${_UL_ETC_DIR} -maxdepth 1 -type f)}")
echo "Total etc support files:${#_UL_ETC_FILES}"
copy_etc_files

# zsh
_ZSH_CFG_FILES=("${(f)$(find ${_ZSH_CFG_DIR} -maxdepth 1 -type f)}")
echo "Total zsh config files:${#_ZSH_CFG_FILES}"

copy_zsh_cfg_files

# vim
copy_vim_cfg_files

# python project files
_PYTHON_FILES=("${(f)$(find ${_PYTHON_DIR} -maxdepth 3 -type f -name '*py')}")
echo "Total python projects:${#_PYTHON_FILES}"
copy_python_files

pushd ~/Code/REPO
./do_commit
