#!/usr/bin/zsh
 
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"
RED_ON_WHITE="\033[0m\033[0;1;31;107m"
WHITE_ON_RED="\033[0m\033[1;37;41m"
AMBER="\033[38;5;208m"
GREY="\033[38;5;250m"

typeset -a DEPS=(LIST.zsh CENTER.zsh)

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh ${DEPS}

# Declarations
typeset -A _STICK_DATA=()
typeset -a _STICK_LIST=()
typeset -a _LOCAL_LIST=()
typeset -A _LIST_ALIAS=("_LOCAL_LIST" "LOCAL" "_STICK_LIST" "STICK")
typeset -A _ALIAS_COLOR=("LOCAL" ${WHITE_ON_GREY} "STICK" ${WHITE_ON_RED})
typeset -A _LIST_COLOR=(LOCAL_DIR CYAN_FG LOCAL_FILE AMBER STICK_DIR GREEN_FG STICK_FILE GREY)
typeset -A _COORDS=(X 10 Y 33 H 10 W 86)

# Constants
_SCRIPT=${0:t}
_CFG_DIR=~/.local/share/${_SCRIPT}
_RSYNC_LOG=${_CFG_DIR}/rsync.log

# Globals
g_CONTEXT=''
g_LOCAL_PATH=''
g_LOCAL_TYPE=d
g_STICK_PATH=''
g_STICK_TYPE=d

# Functions
action_do () {
	local -A PAYLOAD=()
	local ARTIST=''
	local FN=''
	local IN=''
	local LAST_LINE=''
	local LINE=''
	local MSG=''
	local PCT=''
	local PID=''
	local RATE=''
	local SZ=''
	local TM=''
	local K M

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: CONTEXT:${g_CONTEXT}"

	for M in ${_MARKED};do
		IN=$(cut -d'|' -f1 <<<${_LIST[${M}]})
		FN=$(get_inode_fn ${g_LOCAL_PATH} ${IN})
		ARTIST=$(cut -d'|' -f2 <<<${_LIST[${M}]} | cut -d'/' -f1) # Top level dir
		if [[ ${g_CONTEXT} == 'LOCAL' ]];then # Queue copy to STICK
			if [[ -e ${g_STICK_PATH}/${FN:t} ]];then
				msg_box -c -p -PO "${g_STICK_PATH}/${FN:t} exists"
				[[ ${_MSG_KEY} == 'y' ]] && PAYLOAD[${M}]=${FN} # Overwrite if approved
			else
				PAYLOAD[${M}]=${FN} # Add to list
				echo "_LIST:${_LOCAL_LIST[${M}]}" >x
			fi
		else
			PAYLOAD[${M}]=${IN} # Queue delete from STICK
		fi
	done

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: PAYLOAD:${#PAYLOAD}, ARTIST:${ARTIST}"

	[[ -z ${PAYLOAD} ]] && return

	if [[ ${g_CONTEXT} == 'LOCAL' ]];then # Copy from LOCAL to STICK

		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: COPYING - rsync OUT PATH:${g_STICK_PATH}/${ARTIST}"
		[[ ${_DEBUG} -eq 0 ]] && /bin/rm -f ${_RSYNC_LOG} # Clear log

		[[ ! -d ${g_STICK_PATH}/${ARTIST} ]] && mkdir -p ${g_STICK_PATH}/${ARTIST} # Create destination if needed
 		rsync -r -z -h -I -v --info=progress2 --no-R --no-i-r ${(v)PAYLOAD} ${g_STICK_PATH}/${ARTIST} >>${_RSYNC_LOG} 2>&1 & # Background rsync
		PID=$!
		sleep .5

		msg_box -c -C -H2 -I -x${_COORDS[X]} -y${_COORDS[Y]} -h${_COORDS[H]} -w${_COORDS[W]} "Transferring files to ${_STICK_DATA[PATH]}..." # Display transfer window
		msg_box -C -jl "<c>$(str_unicode_line $((_COORDS[W]-4)))<N>" # Header line

		coproc { tail -f --pid=${PID} ${_RSYNC_LOG} }

		while read -p ${COPROC[0]} LINE;do
			if [[ ${?} -ne 0 ]];then
				if grep -q 'total size' ${_RSYNC_LOG};then
					break
				fi
			else
				LINE=$(tr '' '\n' <<<${LINE} | tail -1 | sed '/^[[:space:]]*$/d' | tr -s '[:space:]' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
				[[ ${LINE} =~ "^\s*$" ]] && continue # No blank lines
				if grep -P -q '\d+%' <<<${LINE};then
					SZ=$(cut -d' ' -f1 <<<${LINE})
					PCT=$(cut -d' ' -f2 <<<${LINE})
					RATE=$(cut -d' ' -f3 <<<${LINE})
					TM=$(cut -d' ' -f4 <<<${LINE})
					msg_box -jl -C "<c>${SZ}<N> <g>${PCT}<N> <w>${RATE}<N> <w>${TM}<N>" # Show details
				else
					msg_box -jl -C "<w>${LINE[1,75]}<N>" # Show other
				fi
			fi
			sleep .5
		done
		msg_box -t1 -x $((_COORDS[X] + 4)) -y $((_COORDS[Y] + 31)) "Transfer Complete"

		for M in ${(k)PAYLOAD};do
			list_set_selected ${M} ${_USED_ROW}
		done
	else # Handle stick deletes
		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: DELETING"
		msg_box "Deleting..."

		for M in ${(k)PAYLOAD};do
			find ${g_STICK_PATH} -inum ${PAYLOAD[${M}]} -exec rm -rf {} \;
			list_set_selected ${M} ${_STALE_ROW}
		done

		msg_box_clear
	fi
}

action_warn () {
	local -A COUNT=()
	local ACTION=''
	local DETAIL_TYPE=''
	local MSG=''
	local TYPE=''
	local M

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"

	if [[ ! -w ${g_STICK_PATH} ]];then
		[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: STICK IS READONLY"
		[[ ${g_CONTEXT} == 'LOCAL' ]] && ACTION="Copy" || ACTION="Delete"
		msg_box -H1 -p -PK "<r>Error - Unable to ${ACTION}<N>|Stick is Readonly"
		for M in ${_MARKED};do
			list_set_selected ${M} ${_AVAIL_ROW}
		done
		return -1
	fi
	
	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: CONTEXT${g_CONTEXT}, DETAIL_TYPE:${g_LOCAL_TYPE}"

	if [[ ${g_CONTEXT} == 'LOCAL' ]];then
		DETAIL_TYPE=${g_LOCAL_TYPE}
		TYPE=$(str_pluralize dir ${#_MARKED})
		MSG="Copy ${#_MARKED} ${TYPE} to stick?"
	else
		DETAIL_TYPE=f
		TYPE=$(str_pluralize file ${#_MARKED})
		MSG="Delete ${#_MARKED} ${TYPE} from stick?"
	fi

	msg_box -p -PP -H1 "<I>Please Respond| |${MSG}"

	if [[ ${_MSG_KEY} == 'n' ]];then
		for M in ${_MARKED};do
			list_set_selected ${M} 0
		done
	fi

	return 0
}

check_owner () {
	local OWNER=''
	local GROUP=''
	local PERMS=''
	local DEV_NODE=''
	local MOUNT_POINT=${g_STICK_PATH}
	local USER_UID=$(id -u)
	local USER_GID=$(id -g)

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"

	DEV_NODE=$(mount | grep ${g_STICK_PATH} | tr -s '[:space:]' | cut -d' ' -f1)
	[[ -z ${DEV_NODE} ]] && exit_leave $(err_msg_exit "Unable to determine device node")

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: DEV_NODE:${DEV_NODE}"

	PERMS=$(stat -c'%U|%G' ${g_STICK_PATH})
	OWNER=$(cut -d'|' -f1 <<<${PERMS})
	GROUP=$(cut -d'|' -f2 <<<${PERMS})

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: PERMS:${PERMS}, OWNER:${OWNER}, GROUP:${GROUP}"

	if [[ ${OWNER} == 'root' && ${GROUP} == 'root' ]];then
		msg_box -p -PY -H1 "<r>Warning<N>|Stick is owned by root - unable to write|Remount as ${USER}?"
		if [[ ${_MSG_KEY} == 'y' ]];then
			sudo umount ${g_STICK_PATH}
			sudo mkdir -p ${g_STICK_PATH}
			sudo mount -o uid=$USER_UID,gid=$USER_GID ${DEV_NODE} ${MOUNT_POINT}
			if [[ ${?} -eq 0 ]];then
				msg_box -p -PK "USB remounted. Ownership reassigned to UID:${USER_UID}"
			else
				exit_leave $(err_msg_exit "Unable to change stick permissions")
			fi
		else
			[[ ${?} -ne 0 ]] && exit_leave $(err_msg_exit "Stick is not writable")
		fi
	fi
}

item_decorate () {
	local NDX=${1}
	local _MAX=$((_MAX_COLS - 10))
	local ITEM=$(cut -d'|' -f2 <<<${_LIST[${NDX}]})
	local PWD_MARKER=''
	local TYPE=''
	local DC=''
	local FC=''

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"

	[[ ${ITEM} =~ ${PWD} ]] && PWD_MARKER='./' || PWD_MARKER=''

	[[ ${g_CONTEXT} == 'LOCAL' ]] && ITEM=${${ITEM}##${g_LOCAL_PATH}/} || ITEM=${${ITEM}##${g_STICK_PATH}/}
	ITEM=${ITEM[1,${_MAX}]}
	
	if [[ ${_LIST_SELECTED[${NDX}]} -eq ${_STALE_ROW} ]];then # 2 = deleted
		echo -n "${E_STRIKE}${ITEM}${E_RESET} ${E_ITALIC}${E_RED_FG}deleted${E_RESET}" || echo -n ${ITEM}
	elif [[ ${_LIST_SELECTED[${NDX}]} -eq ${_USED_ROW} ]];then # 3 = copied
		echo -n "${E_STRIKE}${ITEM}${E_RESET} ${E_ITALIC}${E_GREEN_FG}copied${E_RESET}" || echo -n ${ITEM}
	else
		echo "${PWD_MARKER}${ITEM}${RESET}"
	fi
}

list_detail () {
	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: CONTEXT:${g_CONTEXT}, LOCAL_TYPE:${g_LOCAL_TYPE}, STICK_TYPE:${g_STICK_TYPE}"

	if [[ ${g_CONTEXT} == 'LOCAL' ]];then
		[[ ${g_LOCAL_TYPE} == 'f' ]] && g_LOCAL_TYPE='d' || g_LOCAL_TYPE='f'
		load_local ${g_LOCAL_TYPE}
		list_switch LOCAL
	else
		[[ ${g_STICK_TYPE} == 'f' ]] && g_STICK_TYPE='d' || g_STICK_TYPE='f'
		load_stick ${g_STICK_TYPE}
		list_switch STICK
	fi
}

list_switch () {
	local CONTEXT=${1}

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"


	if [[ -n ${CONTEXT} ]];then
		g_CONTEXT=${CONTEXT}
	else
		case ${g_CONTEXT} in
			LOCAL) g_CONTEXT=STICK;load_stick;;
			STICK) g_CONTEXT=LOCAL;;
			*) g_CONTEXT=LOCAL;;
		esac
	fi

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: CONTEXT:${g_CONTEXT}"

	while true;do
		list_reset
		list_show ${(k)_LIST_ALIAS[(r)${g_CONTEXT}]}
	done
}

list_show () {
	local ARRAY_NAME=${1}
	local -A LEVEL_MAP=(d Directories f Files)
	local ALIAS=''
	local DETAIL_TYPE=''
	local PATHLBL=''
	local FC=''
	local DC=''
	local LC=''
	local RC=0

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: ARRAY_NAME:${ARRAY_NAME}"

	ALIAS="${_LIST_ALIAS[${ARRAY_NAME}]}"
	ALIAS="${_ALIAS_COLOR[${ALIAS}]}${ALIAS}${RESET}"

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: CONTEXT:${g_CONTEXT}, LOCAL_TYPE:${g_LOCAL_TYPE}, STICK_TYPE:${g_STICK_TYPE}"

	if [[ ${g_CONTEXT} == 'LOCAL' ]];then
		DETAIL_TYPE=${g_LOCAL_TYPE}
		PATHLBL=$(path_abbv -l40 ${g_LOCAL_PATH})
		DC=LOCAL_DIR
		FC=LOCAL_FILE
		[[ ${g_LOCAL_TYPE} == 'd' ]] && LC=${_LIST_COLOR[${DC}]} || LC=${_LIST_COLOR[${FC}]}
	else
		DETAIL_TYPE=${g_STICK_TYPE}
		PATHLBL=$(path_abbv -l40 ${g_STICK_PATH})
		DC=STICK_DIR
		FC=STICK_FILE
		[[ ${g_STICK_TYPE} == 'd' ]] && LC=${_LIST_COLOR[${DC}]} || LC=${_LIST_COLOR[${FC}]}
	fi

	#set headings
	list_set_header 'printf Content:"${ALIAS} Level:${WHITE_FG}${LEVEL_MAP[${DETAIL_TYPE}]}${RESET} Found:${WHITE_FG}%-d${RESET} Path:${WHITE_FG}%-*s${RESET} Selected:${WHITE_FG}%-d${RESET}  ${_PG}" ${#_LIST} ${#PATHLBL} ${PATHLBL} ${SELECTED_COUNT}'
	list_add_header_break

	#set line item
	list_set_line_item ' 
	printf "${BOLD}${WHITE_FG}%4s${RESET}${_MARKER} ${SHADE}${BAR}${(P)LC}%s${RESET}\n" ${_LIST_NDX} "$(item_decorate ${_LIST_NDX})" 
	'

	list_set_select_action "view"
	list_set_key_callback KEY T FUNC list_switch RET true
	list_set_key_callback KEY D FUNC list_detail RET true
	list_set_custom_keys ". ${WHITE_ON_GREY}Special KEYS${RESET} (${WHITE_FG}T${RESET})oggle List, (${WHITE_FG}D${RESET})etail Level"
	list_set_searchable true

	while true;do
		#get selection
		list_select ${(P)ARRAY_NAME}
		[[ ${?} -eq 0 ]] && RC=1 && break

		#get selections
		_MARKED=($(list_get_selected))
		
		if [[ $(list_get_selected_count) -ne 0 ]];then
			action_warn ${ARRAY_NAME}
			[[ ${?} -ne 0   ]] && continue
			if [[ ${_MSG_KEY} == "y" ]];then
				action_do
			fi
		fi
	done
	return ${RC}
}

load_local () {
	local TYPE=${1}
	local -a RAWLIST=()
	local DL=''
	local FN=''
	local HD=''
	local IN=''
	local MASTER=''
	local NDX=0
	local SUB=''
	local TITLE=''
	local D L

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"
	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: LOCAL_TYPE:${g_LOCAL_TYPE}"

	_LOCAL_LIST=()

	msg_box "Working..."

	if [[ ${TYPE} == 'f' ]];then
		RAWLIST=("${(f)$(find ${g_LOCAL_PATH} -type f ! -path ${g_LOCAL_PATH} -printf '%i|%p|%d\n' | grep -E -i ${SEARCHTERM})}")
	else
		RAWLIST=("${(f)$(find ${g_LOCAL_PATH} -type d ! -path ${g_LOCAL_PATH} -printf '%i|%p|%d\n' | grep -E -i ${SEARCHTERM})}")
	fi

	if [[ ${#RAWLIST} -gt 1000 ]];then
		msg_box -c -p -PY "Processing ${#RAWLIST} rows"
		[[ ${_MSG_KEY} != 'y' ]] && exit_leave $(err_msg_exit I "${RED_FG}Operation Cancelled${RESET}")
	fi

	for L in ${RAWLIST};do
		((NDX++))
		if [[ ${#RAWLIST} -gt 100 ]];then
			tput cup 0 0
			tput el
			printf "\rProcessing line ${WHITE_FG}%d${RESET} of ${WHITE_FG}%d${RESET} lines ${WHITE_FG}%%${BOLD}${GREEN_FG}%.2f${RESET}" ${NDX} ${#RAWLIST} $(( NDX * 100. / ${#RAWLIST} ))
		fi
		IFS='|' read -r IN FN DL <<<${L}
		TITLE=${FN:t}
		HD=${${FN:h}##${g_LOCAL_PATH}}

		if [[ ${TYPE} == 'f' ]];then
			MASTER=''
			SUB=''
			for D in {2..${DL}};do
				if [[ ${D} -eq 2 ]];then
					MASTER=$(cut -d'/' -f${D} <<<${HD})
					[[ -n ${MASTER} ]] && MASTER+="/"
				elif [[ ${D} -eq ${DL} ]];then
					SUB=$(cut -d'/' -f${DL} <<<${HD})
					[[ -n ${SUB} ]] && SUB+="/"
				fi
			done
			_LOCAL_LIST+="${IN}|${MASTER}${SUB}${TITLE}"
		else
			_LOCAL_LIST+="${IN}|${${FN}##${g_LOCAL_PATH}}"
		fi
	done

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: _LOCAL_LIST:${#_LOCAL_LIST} rows"

	if arr_is_populated "${_LOCAL_LIST}";then
		return 0
	else
		return 1
	fi
}

load_stick () {
	local TYPE=${1}
	local -a RAWLIST=()
	local HAS_DIRS=false
	local MAX_DEPTH=''
	local F

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}"
	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: STICK_TYPE:${g_STICK_TYPE}"

	if [[ ${TYPE} == 'f' ]];then
		_STICK_LIST=("${(f)$(find ${g_STICK_PATH} -type f ! -path ${g_STICK_PATH} -printf '%i|%p|%d\n')}")
	else
		_STICK_LIST=("${(f)$(find ${g_STICK_PATH} -type d ! -path ${g_STICK_PATH} -printf '%i|%p|%d\n')}")
	fi

	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: _STICK_LIST:${#_STICK_LIST} rows"

	if arr_is_populated "${_STICK_LIST}";then
		return 0
	else
		clear
		msg_box -x3 -t1 "STICK is empty"
		return 1
	fi
}

#--Begin GetOpts--
local -a OPTIONS
local OPTION
local DESC

read -r -d '' DESC<<EOF
Copy files to USB stick
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTR
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTR+="-${OPTS[${O}]}"
	done
	echo ${OPTSTR}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		t) echo "<FILE_TYPE>";;
		p) echo "<PATH>";;
	esac
}

usage () {
	local -a PENDING_MSGS=(${@})
	local OPTS=$(parse_opts ${OPTSTR})

	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	tabs 5
	(
	echo -e "\n${WHITE_FG}\nUsage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} [<SEARCHTERM>]\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug (repeats increase level)"
	echo -e "${WHITE_FG}-i${RESET} show stick information"
	echo -e "${WHITE_FG}-p${RESET} alternate path (default:\${PWD})"
	echo -e "${WHITE_FG}-n${RESET} run without a stick present"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"
	) >&2

	exit_leave $(err_msg_exit ${PENDING_MSGS})
}

OPTSTR=":HDip:n"
OPTIND=0

INFO_OPT=false
ALT_PATH_OPT=''
NO_STICK=false

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     i) INFO_OPT=true;;
     p) ALT_PATH_OPT=${OPTARG};;
     n) NO_STICK=true;;
     :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: unknown option -${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $(( OPTIND - 1 ))
#--End GetOpts--

# Execution
# Implement SEARCHTERM
[[ ${_DEBUG} -eq 0 ]] && do_smcup
[[ ! -d ${_CFG_DIR} ]] && mkdir -p ${_CFG_DIR} # Create _CFG_DIR

if [[ -n ${ALT_PATH_OPT} ]];then
	stat ${ALT_PATH_OPT} >/dev/null 2>&1
	[[ ${?} -eq 0 ]] && g_LOCAL_PATH=${ALT_PATH_OPT} || exit_leave $(err_msg_exit "Path:${ALT_PATH_OPT} is not available")
else
	g_LOCAL_PATH=${PWD}
fi

[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO} ALT_PATH_OPT:${ALT_PATH_OPT}"

[[ ${#} -ne 0 ]] && SEARCHTERM="${ALT_PATH_OPT}/${1}" || SEARCHTERM='/*'
[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO} SEARCHTERM:${SEARCHTERM}"

if [[ ${NO_STICK} == 'false' ]];then
	STICK_INFO=$(usb_stick_path)
	if [[ ${?} -eq 0 ]];then
		_STICK_DATA[NAME]=$(cut -d'|' -f1 <<<${STICK_INFO})
		_STICK_DATA[DEVICE]=$(cut -d'|' -f2 <<<${STICK_INFO})
		_STICK_DATA[PATH]=$(cut -d'|' -f3 <<<${STICK_INFO})
		g_STICK_PATH=${_STICK_DATA[PATH]}
		if [[ ${INFO_OPT} == 'true' ]];then
			msg_box -p -PK -H1 "<w>USB Stick Information<N>|<c>${_STICK_DATA[NAME]}<N>|<w>Device<N>:${_STICK_DATA[DEVICE]}|<w>Mount<N>:${_STICK_DATA[PATH]}"
			exit_leave
		fi
	else
		usage "No USB stick found"
	fi

	check_owner
	load_stick d
else
	g_STICK_PATH=/tmp
	msg_box -p -PK -H1 "<r>Running without a USB Stick<N>|<c>${_STICK_DATA[NAME]}<N>|<w>All copies will be sent to<N>:${g_STICK_PATH}"
fi

[[ ! -e ${g_STICK_PATH} ]] && exit_leave $(err_msg_exit "STICK PATH:${g_STICK_PATH} does not exist")
if [[ ! -w ${g_STICK_PATH} ]];then
	[[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${0}: STICK IS READONLY"
	msg_box -H1 -p -PK "<r>Error - Unable to access<N>|${g_STICK_PATH} is readonly"
	exit_leave
fi

load_local d

list_switch

exit_leave
