#!/usr/bin/zsh

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

# Constants
_SCRIPT=${0:t}
_LOG=/tmp/${_SCRIPT}.log

# Execution
 
# Args
APP=${1}
if [[ -z ${APP} ]];then
	logit ${_LOG} "Missing argument:APP"
	return 1
else
	logit ${_LOG} "Got APP:${APP}"
fi

WIN_INFO=$(win_id ${APP})
if [[ -n ${WIN_INFO} ]];then
	logit ${_LOG} "Got WIN_INFO:${WIN_INFO} for APP:${APP}"
	WID=$(cut -d'|' -f1 <<<${WIN_INFO})
	logit ${_LOG} "Extracted WID:${WID}"
	wmctrl -i -r ${WID} -b add,maximized_vert,maximized_horz >/dev/null 2>&1
	logit ${_LOG} "${APP} WID:${WID} was MAXIMIZED"
else
	logit ${_LOG} "Unable to get WIN_INFO for ${APP}"
fi
