#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
BLINK="\033[5m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh
_DEPS+=(LIST.zsh SELECT.zsh)
source ${_LIB_DIR}/LIB_DEPS.zsh

# Declarations (dut)
typeset -A _UTILS=(
  external 1
  fstab_info 1
  space 1
  unplug 1
  usbdisks 1
)

typeset -A _UTILS_DESC=(
  external "EXTERNAL:verify or mount external drive"
  fstab_info "FSTAB:display fstab details"
  space "SPACE:show current disk usage"
  unplug "DETACH:safely detach device"
  usbdisks "USB:display usb disk details"
)

# Constants (dut)
_WRAPPER=${0:t}

# Globals (dut)
g_USAGE=false
g_UTIL=''

# Functions (dut)
external () {
  # Declarations and Vars
  local -A _PART _UUID _TYPE _MP _LBL FST_MP
  local -a _LOCAL_LIST
  local _FSTAB=/etc/fstab
  local _MOUNT_ROOT=/media/${USER}
  local DEV_ARG=''

  # Functions
  action_do () {
    local M

    for M in ${_MARKED};do
      if get_status ${_PART[${M}]};then
        manage_dev unmount ${_PART[${M}]}
      else
        manage_dev mount ${_PART[${M}]}
      fi
    done

    for M in ${_MARKED};do
      list_set_selected ${M} ${_STALE_ROW}
    done
  }

  collect_disk_info () {
    local -a DISK_INFO=()
    local DEV UUID TYPE MP LBL
    local LINE
    local NDX=0
    local L U

    while read LINE;do # Get MOUNTPOINTS for fstab entries
      [[ ${LINE:l} =~ '^#' ]] && continue
      [[ ! ${LINE:l} =~ 'uuid' ]] && continue
      L=$(tr -s '[:space:]' <<<${LINE})
      DEV=$(cut -d' ' -f1 <<<${L})
      [[ ${DEV:l} =~ 'uuid=' ]] && UUID=$(cut -s -d'=' -f2 <<<${DEV}) || UUID=${DEV:t}
      MP=$(cut -d' ' -f2 <<<${L})
      FST_MP[${UUID}]="${MP}"
    done < ${_FSTAB}

    # Parse lsblk directly into key-value maps
    lsblk -P -n -o NAME,UUID,FSTYPE,MOUNTPOINT,LABEL | awk '
      /NAME="sd[a-z]+[0-9]+"/ {
      match($0, /NAME="([^"]*)"/, n)
      match($0, /UUID="([^"]*)"/, u)
      match($0, /FSTYPE="([^"]*)"/, f)
      match($0, /MOUNTPOINT="([^"]*)"/, m)
      match($0, /LABEL="([^"]*)"/, l)

      print n[1] "|" u[1] "|" f[1] "|" (m[1] ? m[1] : "Unmounted") "|" l[1] }' | \
      while IFS='|' read -r DEV UUID TYPE MP LBL;do
      ((NDX++))
      _PART[${NDX}]="${DEV}"
      _UUID[${DEV}]="${UUID}"
      _TYPE[${DEV}]="${TYPE}"
      _MP[${DEV}]="${MP}"
      _LBL[${DEV}]="${LBL}"
    done
  }

  manage_dev () {
    local ACTION=${1}
    local DEV=${2}
    local MSTAT=''
    local UUID=''

    case ${ACTION} in
      mount) 
        if get_status ${DEV};then
          [[ ${EXT_VERBOSE_OPT} == 'true' ]] && msg_box -t2 "Device:${DEV} is already mounted"
          return
        fi;;
      unmount) 
        if ! get_status ${DEV};then
          [[ ${EXT_VERBOSE_OPT} == 'true' ]] && msg_box -t2 "Device:${DEV} is already unmounted"
          return
        fi;;
    esac

    UUID=${_UUID[${DEV}]}

    if [[ ${ACTION} == 'mount' ]];then
      [[ ${EXT_VERBOSE_OPT} == 'true' ]] && msg_box -t2 "Mounting drive:${DEV}"
      if [[ -n ${FST_MP[${UUID}]} ]];then
        MSTAT=$(sudo mount ${FST_MP[${UUID}]})
        [[ ${?} -ne 0 ]] && msg_box -p -PK ${MSTAT}
      else
        [[ ! -e ${_MOUNT_ROOT}/${_LBL[${DEV}]} ]] && sudo mkdir ${_MOUNT_ROOT}/${DEV}
        MSTAT=$(sudo mount -t ${_TYPE[${DEV}]} /dev/${_PART[${DEV}]} ${_MOUNT_ROOT}/${_LBL[${DEV}]})
        [[ ${?} -ne 0 ]] && msg_box -p -PK ${MSTAT}
      fi
    else
      [[ ${EXT_VERBOSE_OPT} == 'true' ]] && msg_box -t2 "Unmounting drive:${DEV}"
      if [[ -n ${FST_MP[${UUID}]} ]];then
        MSTAT=$(sudo umount ${FST_MP[${UUID}]})
        [[ ${?} -ne 0 ]] && msg_box -p -PK ${MSTAT}
      else
        MSTAT=$(sudo udisksctl unmount -b /dev/${_PART[${DEV}]})
        [[ ${?} -ne 0 ]] && msg_box -p -PK ${MSTAT}
      fi
    fi
  }

  manage_mounts () {
    local ACTION=${1}
    local DEV=${2:=null}
    local D

    if [[ ${DEV} == 'null' ]];then
      if [[ ${ACTION} == 'mount' ]];then
        [[ ${EXT_VERBOSE_OPT} == 'true' ]] && msg_box -t2 "Mounting all external drives"
        for D in ${_PART};do
          manage_dev mount ${D}
        done
      else
        [[ ${EXT_VERBOSE_OPT} == 'true' ]] && msg_box -t2 "Unmounting all external drives"
        for D in ${_PART};do
          manage_dev unmount ${D}
        done
      fi
    else
      if [[ ${ACTION} == 'mount' ]];then
        manage_dev mount ${DEV}
      else
        manage_dev unmount ${DEV}
      fi
    fi
  }

  get_status () {
    local DEV=${1:=null}
    local D

    if [[ ${DEV} == 'null' ]];then
      for D in ${(k)_PART};do
        [[ ${_SMCUP} == 'true' ]] && do_rmcup
        [[ ${_MP[${_PART[${D}]}]:l} == 'unmounted' ]] && echo "${_PART[${D}]} is unmounted" || echo "${_PART[${D}]} is mounted"
      done
    elif [[ -z ${_MP[${DEV}]} ]];then
      return 1
    else
      [[ ${_MP[${DEV}]:l} != 'unmounted' ]] && return 0 || return 1
    fi
  }

  display_disks () {
    # Set headings
    list_set_header 'printf "Found:${WHITE_FG}%-d${RESET} Partitions\tSelected:${WHITE_FG}%-d${RESET}" ${#_LIST} ${SELECTED_COUNT}'
    list_set_header 'printf " "'
    list_set_header 'printf "%*s %12s %12s %30s %15s" 5 "" "Partition" "Type" "Mount Point" "Label"'
    list_set_header 'printf "%*s ${WHITE_FG}%12s${RESET} ${WHITE_FG}%12s${RESET} ${WHITE_FG}%30s${RESET} ${WHITE_FG}%15s${RESET}" 5 "" $(str_unicode_line 12) $(str_unicode_line 12) $(str_unicode_line 30)  $(str_unicode_line 15)'

    # Set line item
    list_set_line_item '
      local KEY=${_PART[${_LIST_NDX}]};
      local MNT_CLR='';
      [[ ${_MP[${KEY}]:l} == 'unmounted' ]] && MNT_CLR="${RED_FG}" || MNT_CLR="${GREEN_FG}";
      printf "${BOLD}${WHITE_FG}%4s${RESET}${_MARKER} ${SHADE}%12s %12s ${MNT_CLR}%30s${RESET} %15s${RESET}\n" ${_LIST_NDX} "${_PART[${_LIST_NDX}]}" "${_TYPE[${KEY}]}" "${_MP[${KEY}]}" "${_LBL[${KEY}]}"
      
      '

    list_set_prompt_msg '
      printf "${RESET}Press ${WHITE_FG}Home End PgUp PgDn${RESET}, <${GREEN_FG}Enter${RESET}>${RESET} or <${WHITE_FG}q${RESET}>uit${RESET}"
      '
    list_set_select_action "mount/unmount"
    list_set_barlines true
    list_set_reuse_stale true
    list_set_searchable false

    while true;do
      # Get selection
      list_select ${(v)_PART}
      [[ ${?} -eq 0 ]] && break

      # Get selections
      _MARKED=($(list_get_selected))

      if [[ $(list_get_selected_count) -ne 0 ]];then
        action_do
      fi

      collect_disk_info
    done

    exit_leave
  }

  # Execution

  #--Begin GetOpts--
  RESET="\033[m"
  RED_FG="\033[31m"
  WHITE_FG="\033[37m"

  read -r -d '' DESC<<_____EOF
  Utility to mount/unmount external disks
  \tDefault is to display list of external disks
  \tto manage interactively
_____EOF

  parse_opts () {
    local OPTS=${@}
    local -a OPTSTR
    local LETTER_OPT
    local O

    for O in {1..${#OPTS}};do
      [[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
      [[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
      [[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
      OPTSTR+="-${OPTS[${O}]}"
    done
    echo ${OPTSTR}
  }

  opt_exists () {
    local OPT=${1}
    [[ $(( ${OPTIONS}[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
  }

  opt_type () {
    local OPT=${1}
    case ${OPT} in
      d) echo "<DIR>" ;;
      f) echo "<FILE>" ;;
      t) echo "<FILE_TYPE>" ;;
      p) echo "<PARTITION>" ;;
    esac
  }

  usage () {
    local OPTS=$(parse_opts ${OPTSTR})
    local -a PENDING_MSGS=(${@})

    [[ ${_SMCUP} == 'true' ]] && do_rmcup

    (
      tabs 5
      echo -e "${WHITE_FG}Usage${RESET}:${_WRAPPER} ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} [$(opt_type p)]\n"
      echo -e "${WHITE_FG}-H${RESET} help"
      echo -e "${WHITE_FG}-D${RESET} debug"
      echo -e "${WHITE_FG}-m${RESET} mount all"
      echo -e "${WHITE_FG}-u${RESET} unmount all"
      echo -e "${WHITE_FG}-s${RESET} return mount status [ 0:mounted, 1:unmounted ]"
      echo -e "${WHITE_FG}-v${RESET} verbose output"
      echo -e "${WHITE_FG}\nDesc${RESET}:${DESC}"
    ) >&2

    exit_leave $(err_msg_exit ${PENDING_MSGS})
  }

  typeset -a OPTIONS
  OPTSTR=":HDmusv"
  OPTIND=0

  local EXT_MOUNT_OPT=false
  local EXT_UNMOUNT_OPT=false
  local EXT_STATUS_OPT=false
  local EXT_VERBOSE_OPT=false
  local RC=0

  while getopts ${OPTSTR} OPTION ${g_OPTS};do
    case ${OPTION} in
      H) usage ;;
      D) dbg_set_level ;;
      m) EXT_MOUNT_OPT=true ;;
      u) EXT_UNMOUNT_OPT=true ;;
      s) EXT_STATUS_OPT=true ;;
      v) EXT_VERBOSE_OPT=true ;;
      :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage ;;
      \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: ${BOLD}${RED_FG}Unknown option${RESET} -${OPTARG}"; usage ;;
    esac
    [[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
  done
  shift $(( OPTIND - 1 ))
  #--End GetOpts--

  [[ -n ${g_ARGS} ]] && DEV_ARG=${g_ARGS} || DEV_ARG=''

  [[ -n ${DEV_ARG} && -z ${OPTIONS} ]] && exit_leave $(err_msg_exit "Device:${DEV_ARG} requires an option")

  [[ ${EXT_MOUNT_OPT} == 'true' && ${EXT_UNMOUNT_OPT} == 'true' ]] && exit_leave $(err_msg_exit E "Conflicting options:(-m -u)")

  collect_disk_info

  [[ -z ${_PART} ]] && exit_leave "No external drives detected"

  if [[ -z ${OPTIONS} ]];then
    display_disks
  elif [[ ${EXT_MOUNT_OPT} == 'true' ]];then
    manage_mounts mount ${DEV_ARG}
  elif [[ ${EXT_UNMOUNT_OPT} == 'true' ]];then
    manage_mounts unmount ${DEV_ARG}
  elif [[ ${EXT_STATUS_OPT} == 'true' ]];then
    get_status ${DEV_ARG}
    RC=${?}
    [[ -n ${DEV_ARG} ]] && set_exit_value ${RC}
  fi

  exit_leave
}

space () {
  # Declarations and Vars
  local -A HIDDEN=()
  local -A NORMAL=()
  local -a PART_DATA=()
  local -a PART_DETAIL=()
  local -aU PARTITIONS=()
  local DESCENDING=false
  local DIRCNT=0
  local SYSTEM_TOTAL=0

  [[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${_SCRIPT:t}->${0}:" "$(dbg_arglist "${@}")"

  # Functions
  convert_GMK () {
    local ARG=${1}
    local NUM=${ARG[1,-2]}

    [[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${_SCRIPT:t}->${0}:" "$(dbg_arglist "${@}")"

    case ${ARG[-1]} in
      G) echo ${NUM} ;;
      M) bc <<<"scale=8; (${NUM} * 0.0009765625)" ;;
      K) bc <<<"scale=8; (${NUM} * 0.000001)" ;;
      *) echo ${NUM} ;;
    esac
  }

  #--Begin GetOpts--
  RESET="\033[m"
  RED_FG="\033[31m"
  WHITE_FG="\033[37m"

  read -r -d '' DESC<<___EOF
Display disk space consumed by the current directory
___EOF

  parse_opts () {
    local OPTS=${@}
    local -a OPTSTR
    local LETTER_OPT
    local O

    for O in {1..${#OPTS}};do
      [[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
      [[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
      [[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
      OPTSTR+="-${OPTS[${O}]}"
    done
    echo ${OPTSTR}
  }

  opt_exists () {
    local OPT=${1}
    [[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
  }

  opt_type () {
    local OPT=${1}
    case ${OPT} in
      d) echo "<DIR>" ;;
      f) echo "<FILE>" ;;
      t) echo "<FILE_TYPE>" ;;
    esac
  }

  usage () {
    local OPTS=$(parse_opts ${OPTSTR})
    local -a PENDING_MSGS=(${@})

    [[ ${_SMCUP} == 'true' ]] && do_rmcup

    (
      tabs 5
      echo -e "\n${WHITE_FG}Usage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET}\n"
      echo -e "${WHITE_FG}-H${RESET} help"
      echo -e "${WHITE_FG}-D${RESET} debug"
      echo -e "${WHITE_FG}-a${RESET} ascending file sizes"
      echo -e "\n${WHITE_FG}Desc${RESET}:${DESC}"
    ) >&2

    exit_leave $(err_msg_exit ${PENDING_MSGS})
  }

  local -a OPTIONS
  OPTSTR=":HDa"
  OPTIND=0

  DESCENDING=true

  while getopts ${OPTSTR} OPTION ${g_OPTS};do
    case $OPTION in
      H) usage ;;
      D) dbg_set_level ;;
      a) DESCENDING=false ;;
      :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage ;;
      \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: ${BOLD}${RED_FG}Unknown option${RESET} -${OPTARG}"; usage ;;
    esac
    [[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
  done
  shift $(( OPTIND - 1 ))
  #--End GetOpts--

  # Execution
  PARTITIONS=("${(f)$(mount -t ext3,ext4,vfat,ntfs,fuseblk | sed 's/ on.*//' | cut -d'/' -f3)}")

  DIRCNT=$(find . ! -path . -type d 2>/dev/null | wc -l)

  tput cup 0 0
  {
    for P in ${PARTITIONS};do
      [[ ${P} == "b" ]] && continue
      PART_DATA+=$P
    done

    for P in ${PART_DATA};do
      PART_DETAIL+=("${(f)$( sudo df -h /dev/${P} 2>/dev/null | awk 'NR==2{print $0}' | tr -s '[:space:]' | sed 's/ /\|/g')}")
    done

    echo "${WHITE_FG}Disk Space\n${RESET}"
    printf "${WHITE_FG}%16s %6s${RESET} ${RED_FG}%6s${RESET} ${GREEN_FG}%6s ${WHITE_FG}%8s %-20s${RESET}\n" "File System" "Size" "Used" "Avail" "Pct Used" "Mounted On"

    MP=$(findmnt -nT ${PWD} | tr -s '[:space:]' | cut -d' ' -f2)

    for P in ${PART_DETAIL};do
      FS=$(echo $P | cut -d\| -f1)
      SZ=$(echo $P | cut -d\| -f2)
      US=$(echo $P | cut -d\| -f3)
      AV=$(echo $P | cut -d\| -f4)
      PU=$(echo $P | cut -d\| -f5)
      MN=$(echo $P | cut -d\| -f6)
      [[ ${FS} == ${MP} ]] && MN="${MN} $(echo "${BOLD}${GREEN_FG}<-- <-- <--${RESET}")" && SYSTEM_TOTAL=${SZ}
      printf "%16s %6s %6s %6s %8s %-20s\n" ${FS} ${SZ} ${US} ${AV} ${PU} ${MN}
    done

    echo "\n${WHITE_FG}  Current Directory${RESET}:${CYAN_FG}$(pwd)${RESET}"

    HDR=Ascending
    LONGEST=0

    [[ ${DESCENDING} == "true" ]] && SORT=r && HDR=Descending

    if [[ ${DIRCNT} -ne 0 ]];then
      LIST=("${(f)$(sudo du --max-depth 1 2>/dev/null)}")

      for L in ${LIST};do
        SZ=$(echo ${L} | tr -s '[:space:]' | cut  -f1)
        FN=$(echo ${L} | tr -s '[:space:]' | cut  -f2)
        [[ ${FN:t} =~ "^\." ]] && HIDDEN[${FN:t}]=${SZ} || NORMAL[${FN:t}]=${SZ}
        [[ ${#FN:t} -gt ${LONGEST} ]] && LONGEST=${#FN:t}
      done

      [[ ${LONGEST} -lt 20 ]] && LONGEST=18

      DO_HDR=true
      if [[ ${DO_HDR} == "true" ]];then
        DO_HDR=false
        printf "${HDR} order...\n"
        printf "%-10s %-${LONGEST}s %s\n" "KBytes" "Directory" "Human"
        printf "\\u2500%.0s" {1..$(( LONGEST + 17 ))}
        printf "\n"
      fi

      (
        for N in ${(k)NORMAL};do
          printf "${CYAN_FG}%10s ${WHITE_FG}%-${LONGEST}s ${GREEN_FG}%s${RESET}\n" ${NORMAL[${N}]} ${N} $(numfmt --to=iec $(( ${NORMAL[${N}]} * 1024 )))
        done
      ) | sort -k1.6 -n${SORT}

      (
        for H in ${(k)HIDDEN};do
          [[ ${H} == "." ]] && continue
          printf "${CYAN_FG}%10s ${WHITE_FG}%-${LONGEST}s ${GREEN_FG}%s${RESET}\n" ${HIDDEN[${H}]} ${H} $(numfmt --to=iec $(( ${HIDDEN[${H}]} * 1024 )))
        done
      ) | sort -k1.6 -n${SORT}
    fi

    DU=$(sudo du -s 2>/dev/null | sed -e 's/\t/ /' -e 's/\./Total/g')
    TSZ=$(echo ${DU} | tr -s '[:space:]' | cut  -d' ' -f1) # Total PWD size in bytes

    DU=$(sudo du -sh 2>/dev/null | sed -e 's/\t/ /' -e 's/\./Total/g')
    SZ=$(echo ${DU} | tr -s '[:space:]' | cut  -d' ' -f1) # Total PWD size in human readable
    FN=$(echo ${DU} | tr -s '[:space:]' | cut  -d' ' -f2)
    HU=$(numfmt --to=iec $(( ${TSZ} * 1024 ))) # For percentage

    if [[ ${DIRCNT} -ne 0 ]];then
      printf "\\u2500%.0s" {1..$(( LONGEST + 17 ))}
      printf "\n"
      printf "${CYAN_FG}%10s ${WHITE_FG}%-${LONGEST}s ${GREEN_FG}%s${RESET}\n" ${SZ} ${FN} ${HU}
    else
      printf "  "
      printf "\\u2500%.0s" {1..${#DU}}
      printf "\n  ${WHITE_FG}%s${RESET} %s\n" $(cut -d' ' -f1 <<<${DU}) $(cut -d' ' -f2 <<<${DU})
      printf "  "
      printf "\\u2500%.0s" {1..${#DU}}
      printf "\n"
    fi

    # Percentage of total
    D=$(convert_GMK ${HU})
    S=$(convert_GMK ${SYSTEM_TOTAL})
    PCT=$(format_pct $(( D*1.0 / S*1.0 * 100 )))

    echo "\nDirectory:${WHITE_FG}${PWD:t}${RESET} is ${CYAN_FG}${PCT}%${RESET} of total disk space ${RESET}(${WHITE_FG}${SYSTEM_TOTAL}${RESET})"
  } | mypager wait

  exit_leave
}

unplug () {
  # Declarations and Vars
  local -A MOUNTS=()
  local -A STRLEN=()
  local -a LIST=()
  local MD MP
  local NDX=0
  local PART_REGEX="sd[A-Za-z][0-9]"
  local RESPONSE
  local L M

  [[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${_SCRIPT:t}->${0}:" "$(dbg_arglist "${@}")"

  read -r -d '' DESC<<___EOF
Unmount and power off connected external drive
___EOF

  if [[ ${1} == '-H' ]];then
    tabs 5
    echo "${WHITE_FG}\nUsage${RESET}:${_WRAPPER} ${_SCRIPT} [-H] on|off"
    echo "${WHITE_FG} Desc${RESET}:${DESC}"
    exit_leave
  fi

  LIST=("${(f)$(mount | grep ${PART_REGEX} 2>/dev/null | cut -d' '  -f1-3 | sed 's/ on /|/')}") # All sdX

  for L in ${LIST};do
    MD=$(cut -d'|' -f1 <<<${L}) # Device
    MP=$(cut -d'|' -f2 <<<${L}) # Mountpoint
    [[ ${#MD} -gt ${STRLEN[DEV]} ]] && STRLEN[DEV]=${#MD}
    [[ ${#MP} -gt ${STRLEN[DIR]} ]] && STRLEN[DIR]=${#MP}
    MOUNTS[${MD}]=${MP}
  done

  if [[ -n ${MOUNTS} ]];then
    for M in ${(v)MOUNTS};do
      [[ ${PWD} =~ ${M} ]] && exit_leave "${0}:${RED_FG}Unable to unmount${RESET}: change directory to an unmounted location"
    done

    echo "\nSelect device(s) to unplug..."
    printf "\n    ${CYAN_FG}%-*s %-*s${RESET}\n" ${STRLEN[DEV]} "Device" ${STRLEN[DIR]} "Path"
    for M in ${(k)MOUNTS};do
      ((NDX++))
      printf "${WHITE_FG}%2d${RESET}) ${WHITE_FG}%-*s ${MAGENTA_FG}%-*s${RESET}\n" ${NDX} ${STRLEN[DEV]} ${M} ${STRLEN[DIR]} ${MOUNTS[${M}]}
    done
    echo -n "\nSelect drive to unplug:${WHITE_FG}1${RESET}-${WHITE_FG}${#MOUNTS}${RESET} or (${WHITE_FG}a${RESET})ll:"
    read -k1 RESPONSE
    echo

    [[ ${RESPONSE} =~ "^\x0a" ]] && exit_leave "${RED_FG}Operation cancelled${RESET}"

    NDX=0
    for M in ${(k)MOUNTS};do
      ((NDX++))
      if [[ ${RESPONSE:l} == 'a' ]];then
        { udisksctl unmount -f -b ${M} } >/dev/null
      else
        [[ ${NDX} -eq ${RESPONSE} ]] && { udisksctl unmount -f -b ${M} } >/dev/null && break
      fi
    done
    [[ ${?} -ne 0 ]] && echo "An error occurred ejecting ${M}:$?" || echo "Safe to unplug"
  else
    echo
    exit_leave $(err_msg_exit W "No:${PART_REGEX} partitions mounted")
  fi
}

usbdisks () {
  # Declarations and Vars
  local DEV
  local DEVID
  local MOUNTMSG
  local MOUNTPOINT
  local NDX=0
  local USBNAME
  local USBS
  local U F

  [[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${_SCRIPT:t}->${0}:" "$(dbg_arglist "${@}")"

  read -r -d '' DESC<<___EOF
Show usb disk details
___EOF

  if [[ ${1} == '-H' ]];then
    [[ ${_SMCUP} == 'true' ]] && do_rmcup
    tabs 5
    echo "${WHITE_FG}Usage${RESET}:${_WRAPPER} ${_SCRIPT} [-H]"
    echo "${WHITE_FG}\nDesc${RESET}:${DESC}"
    exit_leave
  fi

  for F in /dev/disk/by-id/*;do
    echo ${F:t} | grep -q usb
    [[ ${?} -eq 0 ]] && ((NDX++))
  done

  if [[ ${NDX} -gt 0 ]];then
    USBS=($(ls /dev/disk/by-id/usb*))
    for U in ${USBS};do
      DEV=$(readlink -f ${U})
      if [[ ${U} =~ 'part' ]];then
        MOUNTPOINT=$(mount | grep ${DEV} | tr -s '[:space:]' | cut -d' ' -f3)
        [[ -z ${MOUNTPOINT} ]] && MOUNTMSG="and is ${RED_FG}unmounted${RESET}" || MOUNTMSG="and is ${WHITE_FG}mounted${RESET} at"
        DEVID=''
      else
        MOUNTMSG=''
        USBNAME=$(echo ${U} | cut -d- -f3 | sed 's/_.*//g')
        DEVID="$(lsusb | grep ${USBNAME})\n"
      fi
      echo "USB:${WHITE_FG}${USBNAME}${RESET} is Device:${WHITE_FG}${DEV}${RESET} ${MOUNTMSG} ${WHITE_FG}${MOUNTPOINT}${RESET}"
      echo ${DEVID}
    done
  else
    echo "${RED_FG}No${RESET} ${WHITE_FG}USB${RESET} disk devices found"
  fi
}

fstab_info () {
  # Declarations and Vars
  local -A UUID2DEV
  local -a DEVS=($(ls -la /dev/disk/by-uuid | cut -d \  -f12 | sed s^../..^/dev^))
  local -a UUIDS=($(ls -la /dev/disk/by-uuid | cut -d \  -f10))
  local -i NDX
  local RC
  local STATUS
  local UUID
  local WAS_PARSED
  local M U

  [[ ${_DEBUG} -ge ${_LOW_DBG} ]] && dbg "${_SCRIPT:t}->${0}:" "$(dbg_arglist "${@}")"

  # Execution
  read -r -d '' DESC<<___EOF
Display fstab info
___EOF


  if [[ ${1} == '-H' ]];then
    [[ ${_SMCUP} == 'true' ]] && do_rmcup
    tabs 5
    echo "${WHITE_FG}Usage${RESET}:${_WRAPPER} ${_SCRIPT} [-H]"
    echo "${WHITE_FG}\nDesc${RESET}:${DESC}"
    exit_leave
  fi

  NDX=0
  for U in ${UUIDS};do
    ((NDX++))
    UUID2DEV[${U}]=${DEVS[$NDX]}
  done

  grep -v '#' < /etc/fstab | sed -e 's/	/ /g' | tr -s '[:space:]' | grep -vi swap > /tmp/fst

  local MOUNTS=($(cut -d' ' -f1 < /tmp/fst))
  local POINTS=($(cut -d' ' -f2 < /tmp/fst))
  local TYPES=($(cut -d' ' -f3 < /tmp/fst))
  local OPTIONS=($(cut -d' ' -f4 < /tmp/fst))
  local DUMPS=($(cut -d' ' -f5 < /tmp/fst))
  local PASSES=($(cut -d' ' -f6 < /tmp/fst))

  WAS_PARSED=true # Ensure all fields parsed
  [[ ${#MOUNTS} != ${#POINTS} ]] && WAS_PARSED=false
  [[ ${#MOUNTS} != ${#TYPES} ]] && WAS_PARSED=false
  [[ ${#MOUNTS} != ${#OPTIONS} ]] && WAS_PARSED=false
  [[ ${#MOUNTS} != ${#DUMPS} ]] && WAS_PARSED=false
  [[ ${#MOUNTS} != ${#PASSES} ]] && WAS_PARSED=false
  [[ ${WAS_PARSED} == false ]] && echo 'Parse failed on /etc/fstab' && kill -SIGINT $$

  NDX=0
  echo -e "\n${WHITE_FG}File System Info from /etc/fstab${RESET}"
  for M in ${MOUNTS};do
    ((NDX++))
    UUID=$(echo ${MOUNTS[$NDX]} | sed 's/^.*=//')
    STATUS="${RED_FG}NOT${RESET} mounted"
    mountpoint ${POINTS[$NDX]} >/dev/null 2>&1;RC=${?}
    [[ ${POINTS[$NDX]} == 'none' ]] && STATUS='N/A'
    [[ ${POINTS[$NDX]} != 'none' && ${RC} == 0 ]] && STATUS="${GREEN_FG}Mounted${RESET}"
    echo ${MAGENTA_FG}$(str_unicode_line 55)${RESET}
    echo "      ${WHITE_FG}DEVICE${RESET}: ${MOUNTS[$NDX]} ${UUID2DEV[${UUID}]}"
    echo " ${WHITE_FG}MOUNT POINT${RESET}: ${POINTS[$NDX]} -> ${STATUS}"
    echo "        ${WHITE_FG}TYPE${RESET}: ${TYPES[$NDX]}"
    echo "     ${WHITE_FG}OPTIONS${RESET}: ${OPTIONS[$NDX]}"
    echo "       ${WHITE_FG}DUMPS${RESET}: ${DUMPS[$NDX]}"
    echo "      ${WHITE_FG}PASSES${RESET}: ${PASSES[$NDX]}"
    echo ""
    echo "     ${WHITE_FG}OPTIONS${RESET}: ${OPTIONS[$NDX]}"
    echo "       ${WHITE_FG}DUMPS${RESET}: ${DUMPS[$NDX]}"
    echo "      ${WHITE_FG}PASSES${RESET}: ${PASSES[$NDX]}"
    echo ""
  done
}

# -----------
# --- dut ---
# -----------
#
#--Begin GetOpts--
local -a OPTIONS
local OPTION
local K

read -r -d '' DESC<<EOF
Execute Disk Utilities
\t----------------------
$(for K in ${(k)_UTILS_DESC};do
	printf "\t${WHITE_FG}%s${RESET} - %s\n" ${K} ${_UTILS_DESC[${K}]}
done)
EOF

parse_opts () {
  local OPTS=${@}
  local -a OPTSTR
  local LETTER_OPT
  local O

  for O in {1..${#OPTS}};do
    [[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
    [[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
    [[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
    OPTSTR+="-${OPTS[${O}]}"
  done
  echo ${OPTSTR}
}

opt_exists () {
  local OPT=${1}
  [[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
  local OPT=${1}
  case ${OPT} in
    u) echo "<UTIL>" ;;
  esac
}

usage () {
  local OPTS=$(parse_opts ${OPTSTR})
  local -a PENDING_MSGS=(${@})

  [[ ${_SMCUP} == 'true' ]] && do_rmcup

  (
    tabs 5
    echo -e "\n${WHITE_FG}\nUsage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} $(opt_type u)\n"
    echo -e "${WHITE_FG}-H${RESET} help"
    echo -e "${WHITE_FG}-D${RESET} debug (repeats increase level)"
    echo -e "\n${WHITE_FG}\nDesc${RESET}:${DESC}"
  ) >&2

  exit_leave $(err_msg_exit ${PENDING_MSGS})
}

OPTSTR=":HD"
OPTIND=0

UTIL=''

while getopts ${OPTSTR} OPTION;do
  case $OPTION in
    H) usage ;;
    D) dbg_set_level ;;
    :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage ;;
    \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: unknown option -${OPTARG}"; usage ;;
  esac
  [[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $(( OPTIND - 1 ))
#--End GetOpts--

# Execution
# This is detection of production mode called from another script (--prod will cancel smcup making it friendly to the caller)
g_PROD=false
g_OPTS="${@}"
[[ ${@} =~ '--prod' ]] && g_PROD=true && g_OPTS=$(sed -e 's/--prod//' <<<${g_OPTS} | str_trim)
[[ ${g_PROD} == 'false' && ${_DEBUG} -eq 0 ]] && do_smcup

[[ ${#} -ne 0 ]] && UTIL=${1}

[[ -n ${UTIL} && ${_UTILS[${UTIL}]} -ne 1 ]] && usage "command:${WHITE_FG}${UTIL}${RESET} not found"

if [[ -n ${UTIL} ]];then
  UTIL=${1}
  _SCRIPT=${UTIL}
  g_OPTS=(${(M)@:#-[a-zA-Z0-9]*}); g_ARGS=(${@:#-[a-zA-Z0-9]*})
  g_ARGS=$(sed "s/${_SCRIPT}//" <<<${g_ARGS} | str_trim)
  if [[ ${_UTILS[${UTIL}]} -eq 1 ]];then
    shift
    ${UTIL} ${g_OPTS} ${g_ARGS}
  fi
else
  sel_set_list ${(v)_UTILS_DESC}
  sel_list -sa -O ${CYAN_FG} -C -F"<w>Show Disk Utilities usage or <h>(q)uit<N>" -H"Disk Utilities"

  _SCRIPT=${(k)_UTILS_DESC[(r)${_SEL_VAL}]}
  do_rmcup
  ${_SCRIPT} -H # Call function help

  exit_leave
fi
