#!/usr/bin/zsh

# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

_SCRIPT=${0:t}

usage () {
	echo "Usage:${_SCRIPT} <MOV FILE>"
	echo " Desc:Convert .mov file to .mkv"
	exit 1
}

[[ ${#} -eq 0 ]] && usage
[[ ${#} -gt 1 ]] && echo "${RED_FG}Error${RESET}:Too many args" && usage
[[ ${1:e:l} != 'mov' ]] && echo "${1} is ${RED_FG}NOT${RESET} a MOV file. ${WHITE_FG}MOV${RESET} file required" && usage
[[ ! -f ${1} ]] && echo "${RED_FG}File not found${RESET}:${WHITE_FG}${1}${RESET}" && usage

[[ ${1:e} == 'MOV' ]] && mv ${1} ${1:r}.mov

IN=${1:r}.mov
OUT=${1:r}.mkv

echo "Converting IN:${WHITE_FG}${IN:r}.${ITALIC}${BOLD}${MAGENTA_FG}${IN:e}${RESET} to OUT:${WHITE_FG}${OUT:r}.${ITALIC}${BOLD}${GREEN_FG}${OUT:e}${RESET}"
ffmpeg -hide_banner -loglevel error -y -i "${IN}" -c copy -f matroska "${OUT}"
[[ ${?} -eq 0 ]] && echo "${GREEN_FG}Success${RESET}" || echo "${RED_FG}Errors${RESET}"

exit 0
