#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

_PTS_DIR=/dev/pts
typeset -a _RAWLIST=()
typeset -a _LIST=()

read -r -d '' DESC<<EOF
Display active terminal sessions
\tOption: -c provides a count only
\tOption: -p shows pid of term(s)
EOF

usage () {
	tabs 6
	echo "${WHITE_FG}${(C)0:t}${RESET}: -H -c -p"
	echo " ${WHITE_FG}Desc${RESET}:${DESC}"
	exit
}

term_pids () {
	local -a PIDS

	PIDS=("${(f)$(ps -exo sess,tty | grep pts | sort -u)}")
	printf "%-6s %-6s\n" "TERM" "PID"
	for L in ${PIDS};do
		PID=$(sed 's/^ *//' <<<${L} | cut -d' ' -f1)
		TERM=$(sed 's/^ *//' <<<${L} | cut -d' ' -f2)
		[[ ${PID} == "${TERM_PID}" ]] && MARK='*' || MARK=''
		printf "%-6s %-6s ${WHITE_FG}%s${RESET}\n" ${TERM} ${PID} ${MARK}
	done
	exit
}

# Execution
_RAWLIST=("${(@f)$(find ${_PTS_DIR} ! -path ${_PTS_DIR})}")

for L in ${_RAWLIST};do
	NOT_INT=$(sed 's/^[-+]*[0-9]*//g' <<<${L:t})
	[[ -n ${NOT_INT} ]] && continue
	read -r U P D T IP < <(who | grep ${L:s/\/dev\///} | tr -s '[:space:]') # who will display IP if tty is ssh
	[[ -n ${IP} ]] && SSH=' (ssh)' || SSH='' # ID ssh terms
	_LIST+="${L:s/\/dev\///}${SSH}"
done

[[ ${#_LIST} -gt 1 ]] && TAG=sessions || TAG=session

COUNT_ONLY=false
TERM_PID=$(ps | grep --color=never terminator | head -1 | tr -s ' ' | cut -d' ' -f2)
THIS_TTY=$(tty)

OPT=${1:=null}
while true;do
	[[ ${OPT} == 'null' ]] && break
	case ${OPT} in
		-H) usage;;
		-c) COUNT_ONLY=true;;
		-p) term_pids;;
		-*) echo "Unknown option: ${OPT}"; exit
	esac
	break
done

MSG=''
if [[ ${COUNT_ONLY} == 'true' ]];then
	for L in ${_LIST};do echo ${L};done | grep -c -v ssh
else
	echo "${#_LIST} terminal ${TAG}"
	for T in ${(no)_LIST};do
		[[ "${THIS_TTY:t}" == "${T:t}" ]] && FLAG='*' || FLAG=''
		echo ${T} ${MSG} ${FLAG}
	done
fi
