#!/usr/bin/zsh
 
# Declarations
typeset -a AUDIO=()
typeset -a VIDEO=()
typeset -a LIST=()

# Constants
_YTS_URL_LOG=~/.local/share/yts/yts.url.log
_DOWNLOAD_DIR=~/Downloads/Torrents/Library/web

# Functions
last_file_downloaded () {
	local ST=''
	local FN=''
	local IN=''

	ST=$(stat -c"%W|%i|%n" ${_DOWNLOAD_DIR}/* | sort -t'|' -k1 -r | head -1) # Sort by birth date; grab most recent
	FN=$(cut -d'|' -f3 <<<${ST}) # Filename
	IN=$(cut -d'|' -f2 <<<${ST}) # Inode

	if [[ -e ${FN} ]];then
		echo "${FN}|${IN}"
		return 0
	else
		return 1
	fi
}

# Execution
/usr/local/bin/yt-dlp -Rinfinite "$@"
if [[ ${?} -eq 0 ]];then
	FN=$(last_file_downloaded | cut -d'|' -f1)
	fsub -y -Y ${FN}
	echo "yt download:${@}" >> ${_YTS_URL_LOG}
else
	echo "Command failed:${@}" >> ${_YTS_URL_LOG}
fi
