#!/usr/bin/zsh

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

#Vars
_ENP_MARKER=/tmp/enpass.init
_ENP_PW=''
_ENP_CONFIG="/home/kmiller/.enp"
_WIN_INFO=''
_WDW_ID=''
_WDW_TITLE=''
_TERM_ID=$(win_max -i terminal | cut -d'|' -f2) # Get decimal ID for xdotool

#Get PW
read _ENP_PW < ${_ENP_CONFIG}
_DELAY=1
_SCRIPT=${0:t}
_LOG=/tmp/${_SCRIPT}.log
_ENPASS=/opt/enpass/Enpass 

start_enpass () {
	local ARG=${1}
	local PID

	send-notification ${_DELAY} "Looking for running Enpass instance..."
	PID=($(pgrep -xf ${_ENPASS})) #get PID for Enpass

	if [[ -n ${PID} ]];then
		logit ${_LOG} "Enpass already running...killing instance"
		sudo killall -I enpass
	fi

	#Start Enpass...
	logit ${_LOG} "Starting Enpass..."
	if [[ ${ARG} == 'foreground' ]];then
		echo "Control-C to exit..." >&2
		${_ENPASS} 2>/dev/null
	else
		exec ${_ENPASS} 2>/dev/null & 
	fi

	logit ${_LOG} "Waiting for Enpass to start..."
	send-notification ${_DELAY} "Waiting for Enpass instance..."

	PID=?
	while [[ ! -e /proc/${PID} ]];do
		PID=($(pgrep -xf ${_ENPASS})) #get PID for Enpass
		break
		sleep .2
	done

	logit ${_LOG} "Enpass has started..."
}

pass_login_to_enpass () {
	_WIN_INFO=$(win_max -i -q crash) 
	if [[ -n ${_WIN_INFO} ]];then
		_WDW_ID=$(cut -d'|' -f2 <<<${_WIN_INFO})
		_WDW_TITLE=$(cut -d'|' -f3 <<<${_WIN_INFO})
		logit ${_LOG} "Detected Enpass Crash Window"
		logit ${_LOG} "Sending Escape Key"
		xdotool windowfocus ${_WDW_ID}
		xdotool key --window ${_WDW_ID} Escape
	fi

	logit ${_LOG} "Passing credentials to Enpass..."
	send-notification ${_DELAY} "Sending credentials to Enpass..."

	_WIN_INFO=$(win_max -i enpass) 
	if [[ -n ${_WIN_INFO} ]];then
		_WDW_ID=$(cut -d'|' -f2 <<<${_WIN_INFO})
		/usr/local/bin/system/kbd-toggle off
		/usr/local/bin/system/kbd-flush
		sleep .2
		xdotool windowfocus ${_WDW_ID}
		xdotool type --window ${_WDW_ID} ${_ENP_PW}
		sleep .2
		xdotool key --window ${_WDW_ID} Return
		/usr/local/bin/system/kbd-toggle on
		/usr/local/bin/system/kbd-flush
		xdotool windowfocus ${_TERM_ID}
	fi
}

close_enpass_window () {
	logit ${_LOG} "Closing Enpass window..."
	[[ -n ${_WDW_ID} ]] && xdotool windowclose ${_WDW_ID}
}

#Execution
/bin/rm -f ${_ENP_MARKER}
/bin/rm -f ${_LOG}

xdotool windowfocus ${_TERM_ID}

if [[ ${1} == "-H" ]];then
	echo "Usage: ${0:t} [foreground]" && exit
elif [[ ${1} == "foreground" ]];then
	start_enpass foreground
else
	start_enpass
fi

logit ${_LOG} "$(wmctrl -lp)"

pass_login_to_enpass
close_enpass_window

touch ${_ENP_MARKER}
exit_leave
