#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLINK="\033[5m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

#while read LINE;do
#	echo ${LINE} | cut -d'|' -f1
#done < tense_defs | sort -u
#
#while read LINE;do
#	grep -Ei 'indicative|subjunctive' <<< ${LINE}
#done < test_questions | sort -u

sed -i 's/Indicative_Imperfect_Past/Pluscuamperfecto|Past Perfect/g' test_questions
sed -i 's/Indicative_Present/Presente|Present/g' test_questions
sed -i 's/Indicative_Past_Perfect/Pretérito_Imperfecto|Imperfect Past/g' test_questions
sed -i 's/Indicative_Present_Perfect/Pretérito_Perfecto|Present Perfect/g' test_questions
sed -i 's/Pluscuam_Subjuntivo/Pretérito Pluscuamperfecto de Subjuntivo|Past Perfect Subjunctive/g' test_questions
sed -i 's/Subjunctive_Present_Perfect/Pres_Perfecto_Subj|Present Perfect Subjunctive/g' test_questions
sed -i 's/Subjunctive_Past_Perfect/Pret_Perfecto_Subj|Past Perfect Subjunctive/g' test_questions
sed -i 's/Subjunctive_Imperfect/Subjuntivo_Imperfecto|Imperfect Subjunctive/g' test_questions
sed -i 's/Subjunctive_Present/Subjuntivo_Presente|Present Subjunctive/g' test_questions
