#!/usr/bin/zsh

inline_edit () {
	local PROMPT=${1}
	local CUR_VALUE=${2}
	local PERL_SCRIPT

	read -r -d '' PERL_SCRIPT <<'___EOF'
	use warnings;
	use strict;

	use Term::ReadLine;

	my $term = new Term::ReadLine 'gsq';
	$term->parse_and_bind("set editing-mode vi");

	system('sleep .1;xdotool key Home &');
	while ( defined ($_ = $term->readline($ARGV[0],$ARGV[1])) ) {
		print $_;
		exit;
	}
___EOF

perl -e "$PERL_SCRIPT" ${PROMPT} ${CUR_VALUE}
}

CUR_VALUE=XXX
tput cup $((100)) $((100))
PROMPT="${E_RESET}${E_BOLD}Enter value${E_RESET}:"
NEW_VALUE=$(inline_edit ${PROMPT} ${CUR_VALUE}) #launch line editor
