#!/usr/bin/zsh
#vim: syntax off
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

FILE=movie_2.mkv
SUBDIR=movie_2
HEAD=${PWD}
PATTERN="${HEAD}/${SUBDIR}/${FILE}"

echo "HEAD:${HEAD}"
echo "SUBDIR:${SUBDIR}"
echo "FILE:${FILE}"
echo "PATTERN:${PATTERN}"

echo "\n${WHITE_FG}Delete the FIRST slash and everything before${RESET}"
echo "\${PATTERN#*/}:${PATTERN#*/}"
echo "\n${WHITE_FG}Delete the LAST slash and everything before${RESET}"
echo "\${PATTERN##*/}:${PATTERN##*/}"
echo "\n${WHITE_FG}Delete HEAD${RESET}"
echo "\${\${PATTERN}##\${HEAD}}:${${PATTERN}##${HEAD}}"
echo "\n${WHITE_FG}Delete HEAD and SUBDIR${RESET}"
echo "\${\${PATTERN}##\${HEAD}\${SUBDIR}}:${${PATTERN}##${HEAD}/${SUBDIR}}"

