#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

[[ -n ${1} ]] && LOG_IN=${1} || exit_leave "Need LOG_IN"
[[ -n ${2} ]] && LOG_OUT=${2} || exit_leave "Need LOG_OUT"

log_gen ${LOG_IN} ${LOG_OUT} &

while read -u3 -r LINE;do
	if grep -Eq '' <<<${LINE};then
		sed "s//\n/g" <<<${LINE} | tail -1 # Convert linefeeds to newlines
	else
		echo "${LINE}"
	fi
done 3< ${LOG_OUT}

exit_leave
