#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLINK="\033[5m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh
source ${_LIB_DIR}/VALIDATE.zsh
source ${_LIB_DIR}/PATH.zsh
source ${_LIB_DIR}/DATE.zsh
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/SELECT.zsh
source ${_LIB_DIR}/LIST.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh

# Declarations
typeset -A _CANCELLED=()
typeset -A _CONT_COORDS=()
typeset -A _DOWNLOADS=()
typeset -A _ENG_CODES=(youtube Y rumble R)
typeset -A _FAILED=()
typeset -A _FAV_LIST=()
typeset -A _FIELD_LEN=()
typeset -A _FUTURE=()
typeset -A _INDICATOR_COORDS=()
typeset -A _INFO_COORDS=()
typeset -A _MENU_TYPES=(1 Custom 2 Rumble 3 YouTube)
typeset -A _MSG_DELAY=(SHORT .5 MED 2 LONG 4)
typeset -A _PARTIALS=()
typeset -A _QUERY_OPTS=()
typeset -A _REJECTS=()
typeset -A _RUMBLE_QTYPES=(l live g general u user c channel)
typeset -A _RUMBLE_ROWS=()
typeset -A _SEEN=()
typeset -A _SORT_TABLE=()
typeset -A _STATUS_MSGS=()
typeset -a _RUMBLE_PAGE=()
typeset -a _RUMBLE_QRY_OPTS=(l c u g)
typeset -a _STERMS=()
typeset -a _STRIP_WORDS=()
typeset -aU _LOCAL_LIST=()
typeset -A _MARKED=(1 1)

# Display Constants
_CONT_COORDS=(X 10 Y $(center -h86) H 10 W 86) # Continuous box coords
_INDICATOR_COORDS=(X $(( _CONT_COORDS[X] + 5 )) Y $(( _CONT_COORDS[Y] + _CONT_COORDS[W] - 25 ))) # Alert display coords
_INFO_COORDS=(X $((_CONT_COORDS[X] + 4 )) Y $((_CONT_COORDS[Y] + 3 )) W $((_CONT_COORDS[W] - 6 ))) # Info display coords

# Constants
_CFG_DIR=./cfg
_DOWNLOAD_DIR=~/Downloads/Torrents/Library/web
_ACTION=download
_TRANS_ERR_LIMIT=3
_FIELD_LEN[age]=30
_FIELD_LEN[agetime]=40
_FIELD_LEN[author]=26
_FIELD_LEN[title]=80
_JS_SCRIPT="/usr/local/etc/yts.js"
_MAX_FLEN=85
_MAX_HDR=$(( _CONT_COORDS[W] - 15 ))
_MAX_DL_TITLE=74
_MAX_LS_TITLE=80
_MSG_BOX_DISPLAY_AREA=60 # Limit continuous box clearing on Y axis to preserve alert space
_OBJECT="video"
_SORT_DEFAULT=(youtube 1:a rumble 1:a)
_STRIP_WORDS=("judge napolitano" "official" "^the " " show" "youtube" "channel")
_YTS_DOWNLOAD_LOG=${_CFG_DIR}/yts.downloads
_YTS_ERROR_LOG=${_CFG_DIR}/yts.err.log
_YTS_FAVORITES=${_CFG_DIR}/yts.favorites
_YTS_FAV_NEW=${_CFG_DIR}/yts.favorites.new
_YTS_UPD_MARKER=${_CFG_DIR}/yts-upd.lastrun
_YTS_URL_LOG=${_CFG_DIR}/yts.url.log
_YT_DBG_LOG=${_CFG_DIR}/yt.dbg.log

# Globals
g_CMDLINE_ARGS=false
g_INDICATOR_FLIP=false
g_LAST_CODE_UPD=?
g_LAST_FAV_TYPE=y
g_LAST_SPEED=0
g_LAST_STYPE=0
g_MASK_NDX=1
g_PID=?
g_PREFER_LIVE=''
g_PROXY_CMD=''
g_WHEN=''
g_YTS_LOG=''

local -A QUICK_DL_CHECK=()
local AUTHOR=''
local DEST=''
local DEST_1=''
local DEST_2=''
local DEST_LINE=''
local DUP_LINE=''
local DL_CNT=1
local ETA=''
local FRAME_PAD=8
local HDR1_TXT=0
local HDR2_TXT=0
local HDRS_OUT=false
local HDR_LEN=0
local HRZ_CTR=0
local INFO_TAG=''
local INT_KEY=''
local LAST_MSG=''
local LINE_COLOR=''
local LOG_LINE=''
local MSG=''
local NDX=0
local RETRIES=0
local SPEED=0
local TEXT=''
local TITLE='Testing Parser'
local TRANS_ERR_MSG=''
local LAST_TRANS_ERR=''
local TRANS_ERR_CNT=0
local URL=''
local M

box_center () {
	local TXT=${@} # Message
	local BOX=-4 # Compensate for box border
	local BOX_WIDTH=${_CONT_COORDS[W]} # Width coord

	echo $(center -y${BOX} -t${BOX_WIDTH} ${TXT}) # Return Y coord
}

clean_title () {
	local TITLE=${1}
	echo ${TITLE}
}

keyword_strip () {
	return
}

post_process () {
	return
}

log_add () {
	return
}

get_speed () {
	local SPEED=${@}
	local TYPE=''

	SPEED=$(sed -E 's/^.*at\s+//' <<<${SPEED:l} | cut -d' ' -f1 | sed 's/[/]s//')
	[[ ${SPEED} =~ 'mib' ]] && TYPE=M || TYPE=K
	SPEED=$(sed 's/.ib//' <<<${SPEED})

	[[ ${SPEED} == '100%' ]] && SPEED=0 # Completed

	if validate_is_number ${SPEED};then
		echo "${SPEED}|${TYPE}"
	else
		echo "0|${TYPE}"
	fi
}

download_indicator () {
	local SPEED=$(cut -d'|' -f1 <<<${1} | cut -d. -f1)
	local STYPE=$(cut -d'|' -f2 <<<${1})
	local L_OBJ="\\u23FA"
	local M_OBJ="\\u25CF"
	local R_OBJ="\\u2B24"
	local -A OBJS=()
	local -A OBJS_1=(1 ${L_OBJ} 2 ${M_OBJ} 3 ${R_OBJ})
	local -A OBJS_2=(1 ${R_OBJ} 2 ${M_OBJ} 3 ${L_OBJ})
	local BORDER_COLOR=''
	local DELAY=.3
	local IND_X=$(( _INDICATOR_COORDS[X] + 1 ))
	local IND_Y=$(( _INDICATOR_COORDS[Y] + 7 ))
	local L_SIDE="\\u2770"
	local R_SIDE="\\u2771"
	local MASK=""
	local OBJ_COLOR="${BOLD}${WHITE_FG}" # Default
	local SP_DIR=I

	[[ -z ${SPEED} ]] && SPEED=0
	[[ -z ${g_LAST_SPEED} ]] && g_LAST_SPEED=0

	if [[ ( ${STYPE} == 'M' && ${g_LAST_STYPE} == 'K' ) || ${SPEED} -ge ${g_LAST_SPEED} ]];then 
		SP_DIR=I # Stable or Increasing
	elif [[ ( ${STYPE} == 'K' && ${g_LAST_STYPE} == 'M' ) || ${SPEED} -lt ${g_LAST_SPEED} ]];then 
		SP_DIR=D # Decreasing
	fi

	#logit ${_YT_DBG_LOG} "${0}: SPEED:${SPEED}"

	case ${SPEED} in
		<1-2>) OBJ_COLOR="${BOLD}${RED_FG}";; # YouTube
		<3-4>) OBJ_COLOR="${BOLD}${MAGENTA_FG}";;
		<5-6>) OBJ_COLOR="${BOLD}${CYAN_FG}";;
		<7-10>) OBJ_COLOR="${BOLD}${GREEN_FG}";;
		<11-20>) OBJ_COLOR="${BOLD}${WHITE_FG}";;
		<21-30>) OBJ_COLOR="${BOLD}${CYAN_FG}";;
		<31-40>) OBJ_COLOR="${BOLD}${WHITE_FG}";;
		*) OBJ_COLOR="${BOLD}${GREEN_FG}";;
	esac

	case ${SP_DIR} in
		I) BORDER_COLOR="${BOLD}${GREEN_FG}";;
		D) BORDER_COLOR="${BOLD}${RED_FG}";;
	esac

	OBJS=(${(kv)OBJS_1}) # Init

	if [[ ${g_INDICATOR_FLIP} == 'true' ]];then
		OBJS=(${(kv)OBJS_2})
	fi

	case ${g_MASK_NDX} in
		1) MASK="${BORDER_COLOR}${L_SIDE}${RESET}${OBJ_COLOR}${OBJS[1]}    ${RESET}${BORDER_COLOR}${R_SIDE}${RESET}";;
		2) MASK="${BORDER_COLOR}${L_SIDE}${RESET}${OBJ_COLOR}  ${OBJS[2]}  ${RESET}${BORDER_COLOR}${R_SIDE}${RESET}";;
		3) MASK="${BORDER_COLOR}${L_SIDE}${RESET}${OBJ_COLOR}    ${OBJS[3]}${RESET}${BORDER_COLOR}${R_SIDE}${RESET}";;
	esac

	if [[ ${g_MASK_NDX} -eq 3 ]];then
		[[ ${g_INDICATOR_FLIP} == 'true' ]] && g_INDICATOR_FLIP=false || g_INDICATOR_FLIP=true
	fi

	(( g_MASK_NDX++))
	[[ ${g_MASK_NDX} -gt 3 ]] && g_MASK_NDX=1

 	tcup ${IND_X} ${IND_Y} && echo -n "${MASK}" && sleep ${DELAY}

	g_LAST_SPEED=${SPEED}
	g_LAST_STYPE=${STYPE}
}

# Execution
clear

#yt.log.already
#yt.log.download
#yt.log.future 
 
g_YTS_LOG=${_CFG_DIR}/test.log
case ${1} in
	a) log_gen yt.log.already test.log &;;
	d) log_gen yt.log.download test.log &;;
	f) log_gen yt.log.future test.log &;;
	l) log_gen yt.log.live test.log &;;
	*) echo "Enter a,d,f,l";exit;;
esac

LAST_LOG_SZ=?
TIMEOUT=10
WAIT=0

while true;do
	LOG_SZ=$(wc -c ${g_YTS_LOG} | cut -d' ' -f1)
	if [[ ${LAST_LOG_SZ} != ${LOG_SZ} ]];then
		WAIT=0
		LOG_LINE=$(tail -1 ${g_YTS_LOG}) # Get last log line
		if grep -Eq '' <<<${LOG_LINE};then # Progress section
			LOG_LINE=$(sed "s//\n/g" <<<${LOG_LINE} | tail -1 | str_trim) 2>/dev/null # Convert linefeeds to newlines - get last trimmed
		fi
		# PARSER GOES HERE
			[[ -n ${2} ]] && set -xv
			((NDX++))

			# Handle job reset
			INT_KEY=''
			read -s -t0.1 -k1 INT_KEY
			if [[ ${INT_KEY} == 'k' ]];then 
				job_reset
				logit ${_YT_DBG_LOG} "${0}: JOB CANCELLED"
				MSG="Cancelling download..."
				msg_box -z -t${_MSG_DELAY[MED]} -x${_INFO_COORDS[X]} -y$(box_center ${MSG}) "<w>${MSG}<N>"
				_CANCELLED[${M}]=true
				break
			fi
			
			if [[ ${QUICK_DL_CHECK[${M}]} == 'false' ]];then
				QUICK_DL_CHECK[${M}]=true
				if grep -Eiq '100%' ${g_YTS_LOG};then # Capture very small/quick file download - whole file grep
					logit ${_YT_DBG_LOG} "${0}: COMPLETED (very small file) NDX:${NDX}"
					MSG="Download is complete..."
					msg_box -z -t${_MSG_DELAY[LONG]} -x${_INFO_COORDS[X]} -y$(box_center ${MSG}) "<w>${MSG}<N>"
					_DOWNLOADS[${M}]=true
					logit ${_YT_DBG_LOG} "${0}: POST-PROCESSING"
					post_process
					log_add ${M}
					break
				fi
			fi

			LOG_LINE=$(tail -1 ${g_YTS_LOG}) # Get last log line
			if grep -Eq '' <<<${LOG_LINE};then # Progress section
				LOG_LINE=$(sed "s//\n/g" <<<${LOG_LINE} | tail -1 | str_trim) 2>/dev/null # Convert linefeeds to newlines - get last trimmed
			fi

			if [[ ${HDRS_OUT} == 'false' ]];then 
				case ${LOG_LINE:l} in
					*sleeping*|*hlsnative*|*^\[info\]*)
						MSG="Pre-Processing: ${LOG_LINE[1,60]}"
						logit ${_YT_DBG_LOG} "${0}: PRE-PROCESSING"
						msg_box -z -t${_MSG_DELAY[MED]} -x${_INFO_COORDS[X]} -y$(box_center ${MSG}) "<w>${MSG}<N>"
						continue
						;;
					*'already been'*|*100%*)
						logit ${_YT_DBG_LOG} "${0}: ALREADY DOWNLOADED"
						MSG=$(sed -E "s#^(.*/)(.*)( has.*)#\2#" <<<${LOG_LINE})
						MSG=${MSG[1,60]}
						msg_box -z -t${_MSG_DELAY[LONG]} -x${_INFO_COORDS[X]}  -y$(box_center ${MSG}) "<w>${MSG}<N>|<B>Has already been downloaded<N>"
						_DOWNLOADS[${M}]=true
						break
						;;
					*'will begin'*|*premieres*|*upcoming*)
						logit ${_YT_DBG_LOG} "${0}: FUTURE"
						[[ ! ${LOG_LINE:l} =~ 'minute*|hour*|day*' ]] && g_WHEN='soon' || g_WHEN=$(perl -pe 's/^(.*) in (\d+\s+\w+)(.*)$/\2/g' <<<${LOG_LINE})
						MSG="<w>${TITLE[1,65]}<N>|<r><B>Not yet available<N> - Airing time:<w>${g_WHEN}<N>"
						msg_box -z -t${_MSG_DELAY[LONG]} -x${_INFO_COORDS[X]} -y$(box_center ${TITLE}) "<w>${MSG}<N>"
						_FUTURE[${M}]=true
						_DOWNLOADS[${M}]=false
						break
						;;
					*error*)
						MSG=${LOG_LINE[1,50]}
						TRANS_ERR_MSG=$(cut -d: -f2 <<<${MSG})
						if [[ ${TRANS_ERR_MSG} != ${LAST_TRANS_ERR} ]];then
							((TRANS_ERR_CNT++))
							LAST_TRANS_ERR=${TRANS_ERR_MSG}
							msg_box -c -z -x${_INFO_COORDS[X]} -y$(box_center ${MSG}) "<w>${TRANS_ERR_CNT}<N>:<r>${MSG}<N>"
							logit ${_YT_DBG_LOG} "${0}: TRANSMISSION ERROR ${TRANS_ERR_CNT} of ${_TRANS_ERR_LIMIT}"
							logit ${_YTS_ERROR_LOG} "${0}: ERROR:${TRANS_ERR_CNT}: ${MSG}"
							if [[ ${TRANS_ERR_CNT} -ge ${_TRANS_ERR_LIMIT} ]];then
								_FAILED[${M}]=true
								_DOWNLOADS[${M}]=false
								break
							else
								continue
							fi
						fi
						;;
					*)
						DEST_LINE=$(grep -Ei 'destination' ${g_YTS_LOG}) # Capture destination - whole file grep
						if [[ ${?} -eq 0 ]];then
							logit ${_YT_DBG_LOG} "${0}: GENERATING HEADER"
							DEST=("${(f)$(sed -e "s#${_DOWNLOAD_DIR}/#${_DOWNLOAD_DIR}|#g" -e 's/ \[.*//g' <<<${DEST_LINE})}") # Strip path
							DEST_1=$(cut -d'|' -f1 <<<${DEST})
							DEST_1=$(cut -d']' -f2- <<<${DEST_1} | sed -e "s/^[[:space:]]/<w>/" -e "s/:/<N>:<m>/")
							HDR1_TXT=$(cut -d'|' -f2 <<<${DEST:r} | sed 's/_/ /g') # Clear space fillers and file extension
							HDR1_TXT="<w>Downloading<N>:<m> <c>$(clean_title ${HDR1_TXT} ${_MAX_HDR})<N>"
							HDR2_TXT="$(str_trim ${DEST_1})<N> - <w>${DL_CNT} <N>of <w>${#_MARKED}<N>${INFO_TAG}"
							HDR_LEN=$(( ${#$(msg_nomarkup ${HDR2_TXT})} ))
							HDR_LEN=$(( HDR_LEN + FRAME_PAD ))
							HRZ_CTR=$(center -h${HDR_LEN}) # Horiz center
							[[ ${HDR_LEN} -gt ${_CONT_COORDS[W]} ]] && _CONT_COORDS[W]=${HDR_LEN} && _CONT_COORDS[Y]=${HRZ_CTR} # Adjust frame width/center
							msg_box -c -C -I -H3 -jl -x${_CONT_COORDS[X]} -y${_CONT_COORDS[Y]} -h${_CONT_COORDS[H]} -w${_CONT_COORDS[W]} ${HDR1_TXT}
							msg_box -C -jl ${HDR2_TXT}
							msg_box -C -jl "<c>$(str_unicode_line $(( _CONT_COORDS[W] - 2 )))<N>" # Divider line
							HDRS_OUT=true
							continue
						fi
						;;
				esac
			else # HDRS_OUT == true
				case ${LOG_LINE:l} in
					*eta*)
						SPEED=$(get_speed ${LOG_LINE}) && download_indicator ${SPEED}
						ETA=${LOG_LINE}
						case ${LOG_LINE:l} in
							*100*%) LINE_COLOR='<B><g>';;
							*mib/s*) LINE_COLOR='<w>';;
							*kib/s*) LINE_COLOR='<B><y>';;
						esac
						msg_box -C -jl "${LINE_COLOR}${ETA[1,59]}<N>"
						continue
						;;
					*100%*|*'fixing mpeg-ts'*|*fixupm3u8*|*videoremuxer*)
						logit ${_YT_DBG_LOG} "${0}: COMPLETED"
						msg_box -C -jl "<B><g>Download is complete<N>" # Show completed message
						_DOWNLOADS[${M}]=true
						logit ${_YT_DBG_LOG} "${0}: POST-PROCESSING"
						post_process
						log_add ${M}
						break
						;;
					*error*)
						if grep -Eiq 'cannot reuse http' ${g_YTS_LOG};then # Check for live broadcast
							MSG="Live broadcast - unable to download"
							msg_box -c -z -x${_INFO_COORDS[X]} -y$(box_center ${MSG}) "<r>${MSG}<N>"
							logit ${_YT_DBG_LOG} "${0}: LIVE BROADCAST"
							_FAILED[${M}]=true
							_DOWNLOADS[${M}]=false
							break
						else
							MSG=${LOG_LINE[1,50]}
							TRANS_ERR_MSG=$(cut -d: -f2 <<<${MSG})
							if [[ ${TRANS_ERR_MSG} != ${LAST_TRANS_ERR} ]];then
								((TRANS_ERR_CNT++))
								msg_box -c -z -x${_INFO_COORDS[X]} -y$(box_center ${MSG}) "<w>${TRANS_ERR_CNT}<N>:<r>${MSG}<N>"
								logit ${_YT_DBG_LOG} "${0}: TRANSMISSION ERROR ${TRANS_ERR_CNT} of ${_TRANS_ERR_LIMIT}"
								logit ${_YTS_ERROR_LOG} "${0}: ERROR:${TRANS_ERR_CNT}: ${MSG}"
								LAST_TRANS_ERR=${TRANS_ERR_MSG}
								if [[ ${TRANS_ERR_CNT} -ge ${_TRANS_ERR_LIMIT} ]];then
									_FAILED[${M}]=true
									_DOWNLOADS[${M}]=false
									break
								else
									continue
								fi
							fi
						fi
						;;
				esac
			fi
			# END OF PARSER
	else
		((WAIT++))
		[[ ${WAIT} -gt ${TIMEOUT} ]] && break
	fi
	LAST_LOG_SZ=${LOG_SZ}
	sleep .1
done

exit_leave
