#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

# Force all media files to same codec, frame rate, and bit rate
#ffmpeg -i input1.mp4 -i input2.mp4 -filter_complex \
#"[0:v]fps=30,scale=1920:1080[v0]; \
# [1:v]fps=30,scale=1920:1080[v1]; \
# [v0][0:a][v1][1:a]concat=n=2:v=1:a=1[outv][outa]" \
#-map "[outv]" -map "[outa]" -c:v libx264 -b:v 5000k -c:a aac -b:a 192k output.mp4
#
#Key Parameters Explained

#    fps=30: Forces all video segments to a specific frame rate (e.g., 30 fps) before merging.
#    scale=1920:1080: Ensures all videos have the same resolution (required for the concat filter to work seamlessly).
#    -c:v libx264: Forces the output to a specific codec (H.264).
#    -b:v 5000k: Forces a specific constant or average video bitrate.
#    concat=n=2:v=1:a=1: Merges n inputs into 1 video (v=1) and 1 audio (a=1) stream.

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

# Constants
_DEFAULT_DIR=~/Downloads/Torrents/Library/web
_VID_REGEX='.*\.\(mp4\|avi\|mkv\)$'
_WORKDIR=/tmp/.mp4_merge
_SAFEDIR=/tmp/.mp4_merge_backup
_FLIST=${_WORKDIR}/flist
export BAR_SIZE_RATIO=0.25

# Declarations
typeset -a _FILELIST=()
typeset -a _FILES_TO_MERGE=()

# Vars
_OUT_FILE=vid_merge
_DESTINATION_FILE=${PWD}/${_OUT_FILE}.mp4
_SEARCH_PATH=${_DEFAULT_DIR}

#--Begin GetOpts--
local -a OPTIONS
local OPTION
local DESC

read -r -d '' DESC<<EOF
Merge multiple mp4 files into a single file
\tIf no <SEARCHTERM> is provided, all files in the media path are candidates
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTR
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTR+="-${OPTS[${O}]}"
	done
	echo ${OPTSTR}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		s) echo "<SEARCHTERM>";;
		t) echo "<FILE_TYPE>";;
	esac
}

usage () {
	local -a PENDING_MSGS=(${@})
	local OPTS=$(parse_opts ${OPTSTR})

	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	tabs 5
	(
	echo -e "\n${WHITE_FG}\nUsage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} [$(opt_type s)]\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug (repeats increase level)"
	echo -e "${WHITE_FG}-a${RESET} normalize audio prior to merge"
	echo -e "${WHITE_FG}-m${RESET} move original files to ${_SAFEDIR}"
	echo -e "${WHITE_FG}-o${RESET} $(opt_type f) output file name"
	echo -e "${WHITE_FG}-p${RESET} $(opt_type d) alternate media path [default:${_DEFAULT_DIR}]"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"
	) >&2

	exit_leave $(err_msg_exit "${PENDING_MSGS}")
}

OPTSTR=":HDamo:p:"
OPTIND=0

OUT_FILE=''
ALT_PATH=''
NORM_AUDIO=false
MOVE_FILES=false

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     a) NORM_AUDIO=true;;
     m) MOVE_FILES=true;;
     o) OUT_FILE=${OPTARG};;
     p) ALT_PATH=${OPTARG};;
     :) print -u2 "${_SCRIPT_TAG} ${BOLD}${RED_FG}Option error${RESET}: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${_SCRIPT_TAG} ${BOLD}${RED_FG}Unknown option${RESET} - ${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $(( OPTIND -1 ))
#--End GetOpts--

# Execution
clear
SEARCHTERM=''
[[ ${#} -ne 0 ]] && SEARCHTERM=${@}

if [[ -n ${ALT_PATH} ]];then
	[[ -d ${ALT_PATH} ]] && _SEARCH_PATH=${ALT_PATH} || exit_leave $(err_msg_exit "Invalid path:${ALT_PATH}")
fi

if [[ ! -d ${_WORKDIR} ]];then
	mkdir ${_WORKDIR}
	[[ ${?} -ne 0 ]] && exit_leave "Unable to create _WORKDIR:${_WORKDIR}"
else
	(
	/bin/rm -f ${_WORKDIR}/* 
	) >/dev/null 2>&1 # Clear work area
fi

if [[ ! -d ${_SAFEDIR} ]];then
	mkdir ${_SAFEDIR}
	[[ ${?} -ne 0 ]] && exit_leave "Unable to create _SAFEDIR:${_SAFEDIR}"
fi

echo "Searching for media files in path:${WHITE_FG}${_SEARCH_PATH}${RESET}..."

if [[ -z ${SEARCHTERM} ]];then
	echo "${ITALIC}${BOLD}${YELLOW_FG}No <SEARCHTERM> provided${RESET} - defaulting to all media files in path"
	[[ -n ${OUT_FILE} ]] && _DESTINATION_FILE=${PWD}/${OUT_FILE:r}.mp4
	CMD="find ${_SEARCH_PATH} -regextype 'posix-basic' -maxdepth 1 -type f -regex '${_VID_REGEX}'"
	_FILELIST=("${(f)$(eval ${CMD})}")
else
	echo "Adding all media files matching:\"${WHITE_FG}${SEARCHTERM}${RESET}\""
	[[ -z ${OUT_FILE} ]] && _DESTINATION_FILE=${PWD}/${SEARCHTERM}.mp4 || _DESTINATION_FILE=${PWD}/${OUT_FILE:r}.mp4
	CMD="find ${_SEARCH_PATH} -maxdepth 1 -type f -iname '${SEARCHTERM}*' ! -path ${_SEARCH_PATH}"
	_FILELIST=("${(f)$(eval ${CMD})}")
fi

if [[ -z ${_FILELIST} ]];then
	exit_leave 1 "${_SCRIPT_TAG} ${RED_FG}No media file matches for argument${RESET}:${SEARCHTERM}"
else
	[[ ${NORM_AUDIO} == 'true' ]] && echo "Audio normalization is ${GREEN_FG}active${RESET}"
	echo "DESTINATION_FILE:${_DESTINATION_FILE:h}/${WHITE_FG}${ITALIC}${_DESTINATION_FILE:t}${RESET}"
	[[ -e ${_DESTINATION_FILE} ]] && /bin/rm -f ${_DESTINATION_FILE}

	echo ${MAGENTA_FG}$(str_unicode_line 80)${RESET}
	NDX=0
	for F in ${_FILELIST};do
		((NDX++))
		echo "${WHITE_FG}${NDX}${RESET}) ${F:t}"
	done
	echo ${MAGENTA_FG}$(str_unicode_line 80)${RESET}

	ALERT="Found ${WHITE_FG}${#_FILELIST}${RESET} candidates"
	ACTION="${WHITE_FG}Continue?${RESET}"

	echo -n "\n${ALERT}! ${ACTION}:(${WHITE_FG}y/n${RESET})?"
	read -s -q RESPONSE
	echo
	if [[ ${RESPONSE} == "y" ]];then # Only 'y' will execute task
		echo "Filtering and formatting filelist..."
	else # All other keys terminate
		exit_leave "${RED_FG}Operation cancelled${RESET}..."
	fi
fi

for F in ${(o)_FILELIST};do
	[[ ${F:t:r} == 'vid_merge' ]] && continue
	FTYPE=$(file -b ${F})
	if [[ ${FTYPE:l} =~ 'media|matroska' ]];then
		FN=$(fsub -Cs <<<${F} | tr -d $'\x27') # Compact file names to eliminate problematic spaces in file names
		echo "${GREEN_FG}Adding${RESET} ${F} to worklist..."
		cp ${F} ${_WORKDIR}/${FN:t} >/dev/null 2>&1
		_FILES_TO_MERGE+=${_WORKDIR}/${FN:t}
		echo "${CYAN_FG}Backing up${RESET} ${F} to ${WHITE_FG}${_SAFEDIR}${RESET}..."
		if [[ ${MOVE_FILES} == 'true' ]];then
			echo "Moving ${F} to ${_SAFEDIR}"
			mv -f ${F} ${_SAFEDIR} # >/dev/null 2>&1
		fi
	else
		echo "File:${F} not eligible media - skipped" >&2
	fi
done

# Insert probe here - pass bit rate

if [[ ${NORM_AUDIO} == 'true' ]];then
	echo "Normalizing audio..."
	NDX=0
	for F in ${_FILES_TO_MERGE};do
		((NDX++))
		RECODE_OUT="${_WORKDIR}/recode_${NDX}.mp4"
		export BAR_FILENAME_LENGTH=${#RECODE_OUT:t}
		ffmpeg-bar -y -i ${F} -c:v copy -c:a aac -b:a 48k ${RECODE_OUT}
		echo "file '${RECODE_OUT}'" >> ${_FLIST}
	done
else
	echo "Creating worklist..."
	for F in ${_FILES_TO_MERGE};do
		echo "file '${F}'" >> ${_FLIST}
	done
fi

echo "Merging ${WHITE_FG}${#_FILES_TO_MERGE}${RESET} files..."
ffmpeg -y -loglevel error -f concat -safe 0 -i ${_FLIST} -c copy ${_DESTINATION_FILE}
[[ ${?} -ne 0 ]] && echo "${RED_FG}ffmpeg had errors${RESET}"
[[ -e ${_DESTINATION_FILE} ]] && echo "${_DESTINATION_FILE:h}/${ITALIC}${WHITE_FG}${_DESTINATION_FILE:t}${RESET} was created"

