-P /home/kmiller/Downloads/Torrents/Library/Web
-f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b"
--concurrent-fragments 2
--fixup force
--ignore-errors
--js-runtimes deno:/home/kmiller/.deno/bin
--remote-components ejs:npm
#--remux-video mp4
--restrict-filenames
--retries infinite
--trim-filenames 100 
