-P ~/Downloads/Torrents/Library/web
--concurrent-fragments 4
--extractor-args "youtube:player_client=default"
--fixup force
--format b[ext=mp4]
--ignore-errors
--restrict-filenames
--retries infinite
--trim-filenames 100

