#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

sed -i 's#_VW=/usr/local/bin#_VW=/usr/local/bin/system/vid_watch#' vid_watch.standalone
sed -i 's/vid_to_lib/vid_to_lib.standalone/' vid_watch.standalone


