#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

PID_FN=/tmp/${0:t}.pid
#Functions
on_exit () {
	rm -f ${PID_FN}
	exit
}

#Execution
[[ ! -e ${PID_FN} ]] && echo $$ >${PID_FN}

#Block additional instance
while read PID;do
	ps -p ${PID} >/dev/null 2>&1
	if [[ ${?} -eq 0 ]];then # valid pid
		[[ "$$" != "${PID}" ]] && echo "Only one instance of ${0} allowed" && return
	else
		echo $$ >${PID_FN} # replace stale pid
	fi
done<${PID_FN}

trap "on_exit" EXIT INT TERM

while true;do
	sleep 3
done

