#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

DEFAULT_DB=.spanish_vocab.db
DEFAULT_TABLE=spanish_vocab
LIB=/usr/local/lib

typeset -a SQL

run_sql () {
	sqlite3 ${@} 2>/tmp/sql.errs
	return ${?}
}

read -r -d '' DESC<<EOF
Enter SQL statements
Terminate statements with an empty line
EOF

echo "DEFAULT_DB:${DEFAULT_DB}"
echo "DEFAULT_TABLE:${DEFAULT_TABLE}\n"
echo ${DESC}

while read -r LINE;do
	[[ ${LINE} =~ '^;$' || -z ${LINE} ]] && break
	SQL+=${LINE}
done
SQL+=.quit

echo "${WHITE_FG}Output:${RESET}"
run_sql -echo -header ${DEFAULT_DB} ${SQL}
if [[ ${?} -ne 0 ]];then
	cat /tmp/sql.errs
fi

