#!/usr/bin/zsh
(
cat << tip_nouns_gender
Gender

1. Words that end in “o” are usually masculine
2. Most words ending in “a” are feminine
3. If a word ends with an accented vowel (e.g. “í”) or a consonant other than “d” or “z”, it is probably masculine
4. Certain endings like “ión”, “d” and “z” are likely to be feminine
5. Some words you have to learn that they're masculine or feminine

tip_nouns_gender

NDX=0
LIST=("${(f)$(find . -type f -name '*vocab.dat')}")
if [[ -z ${LIST} ]];then
	echo "No vocabulary file(s) found"
	exit 1
elif [[ ${#LIST} -eq 1 ]];then
	echo "${LIST}"
	FN=${LIST}
else
	echo "Multiple vocab files detected. Enter vocab file to view..."
	for L in ${LIST};do
		((NDX++))
		echo "${NDX}) ${L}"
	done
	echo -n "Enter file to use:"
	read NUM
	[[ -z ${NUM} ]] && echo "Operation cancelled" && exit
	if [[ ${NUM} -le ${#LIST} ]];then
		FN=${LIST[${NUM}]}
	else
		echo "Invalid selection:${NUM}" && exit
	fi
fi

[[ -e ${FN} ]] && grep -E -v '(ar|er|ir|se)\|' ${FN} | grep -Ev 'estar' | grep -Ev 'vocab.dat'
) | mypager
