#!/usr/bin/perl -w
use utf8;
use open ':encoding(utf8)';
binmode(STDOUT, ":utf8");

my $ARG = $ARGV[0] || "null";
my $output = '';

open (my $file, '>', 'format.dat') or die "Could not open file for writing: $!";
die "$!" if $?; 

if ($ARG eq 'noun') {
	$output = `nouns`; 
} elsif ($ARG eq 'verb') {
	$output = `verbs`; 
} else {
	$output = `manage_db -s`; 
}

print $file $output;

open(FILE, "<format.dat");
my @lines = <FILE>;
close(FILE);

foreach (@lines) {
	 print
	 #    chop;
	 #($word, $trans) = (split(/\|/));
	 #write();
}

format =
  @<<<<<<<<<<<<<<<<<<<<<<<<<  @<<<<<<<<<<<<<<<<<<<<<<<<<
  $word,          $trans
.

format STDOUT_TOP =
  @||||||||||||||||||||||||||  Pg @<
  "Spanish Word Translations",    $%

  Spanish                     English     
  -------------------------   -------------------------
.

