#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

typeset -AU LABELS=()

FILES=("${(f)$(find ./*flac -type f)}")
for F in ${FILES};do
	LIST=("${(f)$(metaflac --with-filename --show-all-tags  ${F})}")
	LABELS[$(realpath ${F})]=${(qqq)LIST}
done

typeset -a LIST=()

echo "Labels by File"
for K in ${(k)LABELS};do
	printf "FILE:%s\n" ${K}
	echo ${LABELS[${K}]}
done
