#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

QUESTIONS=./test_questions
TENSE_DEFS=./tense_defs
typeset -A _Q_NDX
typeset -A _T_DEFS
typeset -a _QTEXT

while read LINE;do
	K=$(cut -d '|' -f1 <<<${LINE})
	V=$(cut -d '|' -f2- <<<${LINE})
	_T_DEFS[${K}]=${V}
done < ${TENSE_DEFS}

QUESTIONS_LEN=1
while read LINE;do
	_QTEXT+=${LINE}
	((QUESTIONS_LEN++))
done <<<$(tut blank_lines < ${QUESTIONS})

NDX=1
SEQ=1
for ((L=1; L<QUESTIONS_LEN; L++));do
	if [[ $((${L} % 3)) -eq 0 ]];then
		_Q_NDX[Q${NDX}_A]=${_QTEXT[${L}]}
		((NDX++))
		SEQ=1
	else
		_Q_NDX[Q${NDX}_${SEQ}]=${_QTEXT[${L}]}
		((SEQ++))
	fi
done

for K in ${(onk)_Q_NDX};do
	#printf "KEY:%s VAL:%s\n" ${K} ${_Q_NDX[${K}]}
	MSG=$(${_T_DEFS[${_Q_NDX[${K}]}]} | fold -w40 -s | sed 's/$/|/g')
	#[[ ${K} =~ '_A' ]] && echo ${_T_DEFS[${_Q_NDX[${K}]}]}
done

