#!/usr/bin/env zsh
RESET="\033[m"
RED_FG="\033[31m"
GREEN_FG="\033[32m"
YELLOW_FG="\033[33m"
BLUE_FG="\033[34m"
MAGENTA_FG="\033[35m"
CYAN_FG="\033[36m"
WHITE_FG="\033[37m"

#Constants
_DB_DIR=/home/kmiller/Code/LOCAL/spanish_db
DB=${_DB_DIR}/.spanish.db
_SCRIPT_TAG="${WHITE_FG}[${RESET}${0:t}${WHITE_FG}]${RESET}"

# Declarations
typeset -a _SQL_OUT=()

# Functions
cleanup () {
	[[ -e ${VERB}_tense.dat ]] && /bin/rm -f ${VERB}_tense.dat 
	[[ -e ${VERB}_verb.dat ]] && /bin/rm -f ${VERB}_verb.dat
}

create_spanish_db () {
	[[ ${DEBUG} == 'true' ]] && echo "${WHITE_FG}Executing ${0}${RESET}" >&2
	sqlite3 ${DB} <<____END_SQL
	create table if not exists spanish_tense
	(	verb varchar(20) not null,
		mood varchar(20) not null,
		tense varchar(20) not null,
		p1 varchar(20),
		p2 varchar(20),
		p3 varchar(20),
		p4 varchar(20),
		p5 varchar(20),
		p6 varchar(20),
		irregular boolean,
		primary key(verb,mood,tense)
	);
	create table if not exists spanish_verb
	(	verb varchar(20) not null,
		gerund varchar(20) not null,
		past_participle varchar(20) not null,
		irregular boolean,
		translation varchar(20),
		primary key(verb)
	);
____END_SQL
return ${?}
}

del_spanish_tense_row () {
	[[ ${DEBUG} == 'true' ]] && echo "${WHITE_FG}Executing ${0} with ${@}${RESET}" >&2

	local VERB=$(echo ${@} | cut -d'|' -f1)

	[[ -z ${VERB} ]] && echo "${0:missing} parameter verb" >&2 

	[[ ${DEBUG} == 'true' ]] && echo "${CYAN_FG}delete from spanish_tense where verb = ${VERB}${RESET}"

	sqlite3 ${DB} <<____END_SQL
	delete from spanish_tense where verb = "${VERB}";
____END_SQL
return ${?}
}

del_spanish_verb_row () {
	[[ ${DEBUG} == 'true' ]] && echo "${WHITE_FG}Executing ${0} with ${@}${RESET}" >&2
	local VERB=${1}

	[[ -z ${VERB} ]] && echo "${0}:missing spanish verb" >&2 

	[[ ${DEBUG} == 'true' ]] && echo "${CYAN_FG}delete from spanish_verb where verb = ${VERB};${RESET}"

	sqlite3 ${DB} <<____END_SQL
	delete from spanish_verb where verb = "${VERB}";
____END_SQL
return ${?}
}

get_spanish_tense_row () {
	[[ ${DEBUG} == 'true' ]] && echo "${WHITE_FG}Executing ${0} with ${@}${RESET}" >&2
	local VERB=$1

	[[ -z ${VERB} ]] && echo "${0:missing} parameter verb" >&2 

	[[ ${DEBUG} == 'true' ]] && echo "${CYAN_FG}select * from spanish_tense where verb = ${VERB};${RESET}"

	_SQL_OUT=("${(f)$(
	sqlite3 ${DB} <<____END_SQL
	select * from spanish_tense where verb = "${VERB}";
____END_SQL
	)}")
	return ${?}
}

get_spanish_verb_row () {
	[[ ${DEBUG} == 'true' ]] && echo "${WHITE_FG}Executing ${0} with ${@}${RESET}" >&2
	local VERB=${1}
	local -a SQL_OUT=()

	[[ -z ${VERB} ]] && echo "${0}:missing spanish verb" >&2 

	[[ ${DEBUG} == 'true' ]] && echo "${CYAN_FG}select * from spanish_verb where verb = ${VERB};${RESET}"

	_SQL_OUT=("${(f)$(
	sqlite3 ${DB} <<____END_SQL
	select * from spanish_verb where verb = "${VERB}";
____END_SQL
	)}")
	return ${?}
}

import () {
	local VERB=${1}

	[[ ${DEBUG} == 'true' ]] && echo "${WHITE_FG}Executing ${0} with ${@}${RESET}" >&2
	sqlite3 ${DB} <<____END_SQL
.mode csv
.import ${VERB}_tense.dat spanish_tense
.import ${VERB}_verb.dat spanish_verb
____END_SQL
return ${?}
}

#--Begin GetOpts--
RESET="\033[m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"

SCRIPT=${0:t}
function parse_opts {
	local OPTS=$@
	local -a OPTSTRING
	for O in {1..${#OPTS}};do
		[[ $O -eq 1 && ${OPTS[$O]} == ":" ]] && continue
		[[ $O -gt 1 && ${OPTS[$O]} == ":" ]] && OPTSTRING+="<VERB>" && continue
		OPTSTRING+="-${OPTS[$O]}"
	done
	echo $OPTSTRING
}

function usage {
	local OPTS=$(parse_opts $OPTSTR)
	local MSG=${@}

	echo -e "\n${WHITE_FG}Usage${RESET}: $SCRIPT ${WHITE_FG}[${RESET} $OPTS ${WHITE_FG}]${RESET}\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug"
	echo -e "${WHITE_FG}-c${RESET} Create new database"
	echo -e "${WHITE_FG}-a${RESET} Append data"
	echo -e "${WHITE_FG}-u${RESET} Update data"
	echo -e "${WHITE_FG}-d${RESET} Delete data"
	echo -e "${WHITE_FG}-s${RESET} Select data"
	echo -e "\n${WHITE_FG}DESC${RESET}:Manage the spanish database\n"

	[[ -n ${MSG} ]] && echo ${MSG}
	exit
}

OPTSTR=":HDca:u:d:s:"

DEBUG=false
CREATE=false
APPEND=false
UPDATE=false
DELETE=false
SELECT=false
OPTIND=0
VERB=?
while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) DEBUG=true;;
     c) CREATE=true;;
     u) UPDATE=true; VERB=${OPTARG};;
     d) DELETE=true; VERB=${OPTARG};;
     a) APPEND=true; VERB=${OPTARG};;
     s) SELECT=true; VERB=${OPTARG};;
     :) print -u2 "${SCRIPT}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${SCRIPT}: unknown option -${OPTARG}"; usage;;
	esac
done
shift $((OPTIND -1))
#--End GetOpts--

# Execution
[[ ${VERB} == '?' ]] && usage "${_SCRIPT_TAG} ${RED_FG}Missing argument${RESET}:<VERB>"

if [[ ${CREATE} == "true" ]];then
	echo "Creating new spanish database"
	echo "${WHITE_FG}This will ${RED_FG}delete ${WHITE_FG}all existing data${RESET}"
	echo -n "Proceed(y/n)?:"
	read -q RESPONSE
	[[ ${RESPONSE} == "n" ]] && exit
	echo
	rm -f ${DB} && create_spanish_db
fi

if [[ ${UPDATE} == "true" || ${APPEND} == "true" ]];then
	[[ ! -e ${VERB}_tense.dat ]] && echo "${_SCRIPT_TAG} ${RED_FG}Data file not found:${WHITE_FG}${VERB}_tense.dat${RESET}" && exit
	[[ ! -e ${VERB}_verb.dat ]] && echo "${_SCRIPT_TAG} ${RED_FG}Data file not found:${WHITE_FG}${VERB}_verb.dat${RESET}" && exit
fi

if [[ ${DELETE} == "true" ]];then
	get_spanish_verb_row ${VERB}
	if [[ -z ${_SQL_OUT} ]];then
		echo "${_SCRIPT_TAG} ${RED_FG}Delete failed${RESET} for verb:${WHITE_FG}${VERB}${RESET}. No data exists."
		exit
	else
		for L in ${_SQL_OUT};do
			printf "%s\n" ${L}
		done
	fi

	echo "Deleting ${VERB} from spanish database"
	del_spanish_verb_row ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"

	del_spanish_tense_row ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"
fi

if [[ ${UPDATE} == "true" ]];then
	get_spanish_verb_row ${VERB}
	if [[ -z ${_SQL_OUT} ]];then
		echo "${_SCRIPT_TAG} ${RED_FG}Update failed${RESET} for verb:${WHITE_FG}${VERB}${RESET}. No data exists."
		exit
	else
		for L in ${_SQL_OUT};do
			printf "%s\n" ${L}
		done
	fi

	echo "Updating ${VERB} in spanish database"
	del_spanish_verb_row ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"

	del_spanish_tense_row ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"

	import ${VERB}

	get_spanish_verb_row ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"

	get_spanish_tense_row ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"
	cleanup
fi

if [[ ${APPEND} == "true" ]];then
	get_spanish_verb_row ${VERB}
	if [[ -n ${_SQL_OUT} ]];then
		echo "${_SCRIPT_TAG} ${RED_FG}Append failed${RESET} for verb:${WHITE_FG}${VERB}${RESET}"
		echo "Verb:${WHITE_FG}${VERB}${RESET} already exists - use update instead"
		exit
	fi

	echo "Appending ${VERB} to spanish database"
	import ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"

	get_spanish_verb_row ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"

	get_spanish_tense_row ${VERB}
	[[ ${DEBUG} == 'true' ]] && echo "Returned code:${?}"
	cleanup
fi

if [[ ${SELECT} == "true" ]];then
	clear
	echo "${CYAN_FG}Selecting data for${WHITE_FG}:${VERB}${RESET} from ${WHITE_FG}${DB}${RESET}\n"

	get_spanish_verb_row ${VERB}
	if [[ -z ${_SQL_OUT} ]];then
		echo "Master query for:${VERB} was unsuccessful..."
	else
		for L in ${_SQL_OUT};do
			printf "%s\n" ${L}
		done
	fi

	get_spanish_tense_row ${VERB}
	if [[ -z ${_SQL_OUT} ]];then
		echo "Tense query for:${VERB} was unsucessful..."
	else
		for L in ${_SQL_OUT};do
			printf "%s\n" ${L}
		done
	fi
fi


