#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

err_msg_exit () {
	local E_MSG=''
	local E_TYPE=''
	local LABEL=''
	local LCOLOR=''

	[[ ${_DEBUG} -ge ${_MID_DBG} ]] && dbg "${functrace[1]} called ${0}:${LINENO}: ARGC:${#@}"

	if [[ ! -t 0 ]];then
		read E_MSG
		E_TYPE=E
	else
		if [[ ${#} -eq 0 ]];then
			return 1 # No args
		elif [[ ${#} -eq 1 ]];then
			E_MSG=${1}
			E_TYPE=E # Default type
		elif [[ ${#} -eq 2 ]];then
			E_TYPE=${1}
			E_MSG=${2}
		fi
	fi

	case ${E_TYPE} in 
		W) LABEL="Warning";LCOLOR=${ITALIC}${BOLD}${MAGENTA_FG};;
		E) LABEL="Error";LCOLOR=${ITALIC}${BOLD}${RED_FG};;
		I) LABEL="Info";LCOLOR=${ITALIC}${CYAN_FG};;
	esac

	if [[ -n ${E_MSG} ]];then
		local IS_FILE=$(rev <<<$(cut -d: -f1 <<<$(rev <<<${E_MSG})))
		if [[ ${IS_FILE} =~ ".\.." ]];then
			E_MSG="$(cut -d: -f1 <<<${E_MSG}):${WHITE_FG}${IS_FILE}${RESET}"
		else
			[[ ${E_MSG} =~ ":" ]] && E_MSG=$(perl -pe "s/^(.*:)(\w+)(.*)$/\1\e[37m\2\e[m\3/" <<<${E_MSG})
		fi
		printf "[${WHITE_FG}%s${RESET}]:[${LCOLOR}${LABEL}${RESET}] %s" ${_SCRIPT} "$(echo ${E_MSG})"
	fi
}

err_msg_exit "${@}"

