#!/usr/bin/env python3

import time
from sys import argv
import gi
gi.require_version('Notify', '0.7')
from gi.repository import Notify

script, duration, text = argv

duration = int(duration)

Notify.init ("notify")

Notification=Notify.Notification.new ("", text, "dialog-information")

Notification.show()

time.sleep(duration)

Notification.close()
