#!/usr/bin/zsh
 
lscolors () {
	# Declarations
	local -A OBJ_COLOR
	local -A ATTRIBUTE_CODES=(00 none 01 bold 04 underscore 05 blink 07 reverse 08 concealed)
	local -A FOREGROUND_COLOR_CODES=(30 black 31 red 32 green 33 yellow 34 blue 35 magenta 36 cyan 37 white)
	local -A BACKGROUND_COLOR_CODES=(40 black 41 red 42 green 43 yellow 44 blue 45 magenta 46 cyan 47 white)
	local -A CC
	local -a FOUND_TYPES
	local -a FOUND_EXT
	local -A FIELD_LEN
	local -a COLORS
	local -a ANSI
	local DESC
	local NDX
	local WIDTH
	local C F K T

	# Constants
	local _DIR_COLORS=/etc/zsh/DIR_COLORS
	local _CANDIDATES=("${(@f)$(sudo find . -maxdepth 1 ! -path . 2>/dev/null)}")

	# Functions
	set_color_code () {
		local CODE=${1}
		local K

		if [[ ${CODE} -ge 0 && ${CODE} -le 8 ]];then
			echo ${ATTRIBUTE_CODES[${CODE}]}
		elif [[ ${CODE} -ge 30 && ${CODE} -le 37 ]];then
			echo ${FOREGROUND_COLOR_CODES[${CODE}]}
		elif [[ ${CODE} -ge 40 && ${CODE} -le 47 ]];then
			echo ${BACKGROUND_COLOR_CODES[${CODE}]}
		else
			echo "normal"
		fi
	}

	get_ansi () {
		local CODE=${1}

		if [[ ${CODE} -eq 99 ]];then
			echo ''
		else
			echo "\033[${CODE}m"
		fi
	}

	parse_code_string () {
		local CODE_STRING=${1}
		local CODE
		local -a CODES
		local X
		local LIMIT=$(( ${#CODE_STRING} + 1 ))

		if [[ -n ${CODE_STRING} ]];then
			for ((X=1;X<=${LIMIT};X++));do
				if [[ ${CODE_STRING[${X}]} == ';' || ${X} == ${LIMIT} ]];then
					CODES+=${CODE}
					CODE=''
				else
					CODE+=${CODE_STRING[${X}]}
				fi
			done
		else
			CODES+=99
		fi

		echo ${CODES}
	}

	parse_dir_colors () {
		local LINE
		local EXT
		local CODE_STRING
		local F1
		local F2

		while read LINE;do
			[[ ${LINE} =~ "^#" ]] && continue
			if [[ ${LINE} =~ "^\.[A-Za-z0-9]" ]];then
				EXT=$(cut -d ' ' -f1 <<<${LINE})
				CODE_STRING=$(cut -d ' ' -f2- <<<${LINE} | sed -e 's/#.*$//g' -e 's/\t//g')
				OBJ_COLOR[${EXT}]=${CODE_STRING}
			else
				EXT=$(cut -d ' ' -f1 <<<${LINE})
				CODE_STRING=$(cut -d ' ' -f2- <<<${LINE} | sed -e 's/#.*$//g' -e 's/\t//g')
				OBJ_COLOR[${EXT}]=${CODE_STRING}
			fi
		done < ${_DIR_COLORS}
	}

	# Execution
	read -r -d '' DESC<<___EOF
View color assignments for listings
\tof files in the current directory
___EOF

	if [[ ${1} == '-H' ]];then
		[[ ${_SMCUP} == 'true' ]] && do_rmcup
		tabs 5
		echo "${WHITE_FG}\nUsage${RESET}:${_WRAPPER} ${_SCRIPT} [-H]\n"
		echo "${WHITE_FG}\nDesc${RESET}:${DESC}"
		exit_leave
	fi

	parse_dir_colors

	# Parse local file types...
	for F in ${_CANDIDATES};do
		if [[ -d ${F} && -k ${F} && ! -O ${F} && -w ${F} ]];then
			FOUND_TYPES+="STICKY_OTHER_WRITABLE"
		elif [[ -d ${F} && ! -k ${F} && ! -O ${F} && -w ${F} ]];then
			FOUND_TYPES+="OTHER_WRITABLE"
		elif [[ -d ${F} && -k ${F} && ! -O ${F} && ! -w ${F} ]];then
			FOUND_TYPES+="STICKY_DIR"
		elif [[ -h ${F} ]];then
			FOUND_TYPES+="LINK"
		elif [[ -S ${F} ]];then
			FOUND_TYPES+="SOCK"
		elif [[ -b ${F} ]];then
			FOUND_TYPES+="BLK"
		elif [[ -c ${F} ]];then
			FOUND_TYPES+="CHR"
		elif [[ -u ${F} ]];then
			FOUND_TYPES+="SETUID"
		elif [[ -g ${F} ]];then
			FOUND_TYPES+="SETGID"
		elif [[ -k ${F} ]];then
			FOUND_TYPES+="STICKY_FILE"
		elif [[ -p ${F} ]];then
			FOUND_TYPES+="NAMED-PIPE"
		elif [[ -d ${F} ]];then
			FOUND_TYPES+="DIR"
		elif [[ -x ${F} ]];then
			FOUND_TYPES+="EXEC"
		elif [[ -f ${F} ]];then
			FOUND_TYPES+="FILE"
		fi
		[[ ${#FOUND_TYPES[-1]} -gt ${FIELD_LEN[TYPE]} ]] && FIELD_LEN[TYPE]=${#FOUND_TYPES[-1]}
	done 

	# Parse local file extensions...
	for F in ${_CANDIDATES};do
		[[ -d ${F} ]] && continue
		T=${F:t}
		[[ -n ${T:r} && -n ${T:e} ]] && FOUND_EXT+=".${T:e}"
		[[ ${#FOUND_EXT[-1]} -gt ${FIELD_LEN[EXT]} ]] && FIELD_LEN[EXT]=${#FOUND_EXT[-1]}
	done

	[[ ${FIELD_LEN[TYPE]} -gt ${FIELD_LEN[EXT]} ]] && WIDTH=${FIELD_LEN[TYPE]} || WIDTH=${FIELD_LEN[EXT]}
	[[ ${WIDTH} -lt 6 ]] && WIDTH=6

	printf "\n${WHITE_FG}%-*s %26s${RESET}\n" ${WIDTH} "Object" "Colors and Attributes"
	printf "${MAGENTA_FG}%-*s %26s${RESET}\n" ${WIDTH} $(str_unicode_line 6) $(str_unicode_line 21)

	NDX=0
	for K in ${(ku)FOUND_TYPES};do
		COLORS=()
		ANSI=()
		for C in ${$(parse_code_string ${OBJ_COLOR[${K}]})};do
			COLORS+=$(set_color_code ${C})
			ANSI+=$(get_ansi ${C})
		done
		[[ -z ${ANSI} ]] && ANSI=" "
		printf "${ANSI}%-*s${RESET} %-s %-s %-s\n" $(( WIDTH + 4 )) ${K} ${COLORS[1]} ${COLORS[2]} ${COLORS[3]}
	done

	for K in ${(ku)FOUND_EXT};do
		COLORS=()
		ANSI=()
		for C in ${$(parse_code_string ${OBJ_COLOR[${K}]})};do
			COLORS+=$(set_color_code ${C})
			ANSI+=$(get_ansi ${C})
		done
		[[ -z ${ANSI} ]] && ANSI=" "
		printf "${ANSI}%-*s${RESET} %-s %-s %-s\n" $(( WIDTH + 4 )) ${K} ${COLORS[1]} ${COLORS[2]} ${COLORS[3]}
	done
	echo
}

lscolors
