#!/usr/bin/zsh
path_strip_options () {
	local LINE=${@:Q}

	echo "LINE:${LINE}"
	while true;do # Strip options
		set -xv
        grep -qP '^\-\w+' <<<${LINE}
        [[ ${?} -ne 0 ]] && break
        perl -pe 's/(\-\w+)\s+(.*)/1:\1 2:\2/g' <<<${LINE}
		set +xv;read
	done

	echo ${LINE}
}

path_strip_options '-p'\''Galloway'\'' '\''https://www.youtube.com/watch?v=bYHrA5k2ezs'\'
