#!/usr/bin/zsh

#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

_LIB_DIR=/usr/local/lib

#Imports
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/ANSI.zsh
source ${_LIB_DIR}/ARRAY.zsh
source ${_LIB_DIR}/EXIT.zsh
source ${_LIB_DIR}/MSG.zsh
source ${_LIB_DIR}/STR.zsh
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

box_coords_overlap () {
	local TAG_1=${1}
	local TAG_2=${2}

	local -A BOX_A_COORDS=($(box_coords_get ${TAG_1}))
	local -A BOX_B_COORDS=($(box_coords_get ${TAG_2}))

	local -i L1_X=${BOX_A_COORDS[X]}
	local -i R1_X=$(( BOX_A_COORDS[X] + BOX_A_COORDS[H] -1 ))
	local -i L1_Y=${BOX_A_COORDS[Y]}
	local -i R1_Y=$(( BOX_A_COORDS[Y] + BOX_A_COORDS[W] -1 ))

	local -i L2_X=${BOX_B_COORDS[X]}
	local -i R2_X=$(( BOX_B_COORDS[X] + BOX_B_COORDS[H] -1 ))
	local -i L2_Y=${BOX_B_COORDS[Y]}
	local -i R2_Y=$(( BOX_B_COORDS[Y] + BOX_B_COORDS[W] -1 ))

	local STATE=OVERLAP
	[[ ${L2_X} -gt ${R1_X} ]] && STATE=CLEAR
	[[ ${L2_Y} -gt ${R1_Y} ]] && STATE=CLEAR
	echo ${STATE}:${L2_X}:${R1_X}:${L2_Y}:${R1_Y}
}

clear

msg_box -TMSG1 -jl -x10 -y10 -w30 -h10 "<w>MSG1 Left Message<N>|XXX|YYY|ZZZ"
msg_box -TMSG2 -H1 -x12 -y55 -w30 -h10 "<w>MSG2 Center Message<N>|XXX|YYY|ZZZ"
msg_box -TMSG3 -jl -x14 -y20 -w30 -h10 "<w>MSG3 Left Message<N>|XXX|YYY|ZZZ"
msg_box -TMSG4 -H1 -x16 -y55 -w30 -h10 "<w>MSG4 Center Message<N>|XXX|YYY|ZZZ|111|222|333"
msg_box -TMSG5 -H1 -x16 -y95 -w30 -h10 "<w>MSG5 Right Message<N>|XXX|YYY|ZZZ|111|222|333"


#box_coords_dump

STATE=$(box_coords_overlap MSG2 MSG4)
IFS=: read ST L2X R1X L2Y R1Y <<<${STATE}
tcup ${L2X} ${L2Y}; echo -n "${GREEN_FG}L(${L2X},${L2Y})${RESET}"
tcup ${R1X} ${R1Y}; echo -n "${RED_FG}R(${R1X},${R1Y})${RESET}"
tcup 0 0;echo -n "MSG2 MSG4:${ST} ${L2X} > ${R1X} ${L2Y} > ${R1Y}"

STATE=$(box_coords_overlap MSG1 MSG4)
IFS=: read ST L2X R1X L2Y R1Y <<<${STATE}
tcup ${L2X} ${L2Y}; echo -n "${GREEN_FG}L(${L2X},${L2Y})${RESET}"
tcup ${R1X} ${R1Y}; echo -n "${RED_FG}R(${R1X},${R1Y})${RESET}"
tcup 1 0;echo -n "MSG1 MSG4:${ST} ${L2X} > ${R1X} ${L2Y} > ${R1Y}"

STATE=$(box_coords_overlap MSG1 MSG2)
IFS=: read ST L2X R1X L2Y R1Y <<<${STATE}
tcup ${L2X} ${L2Y}; echo -n "${GREEN_FG}L(${L2X},${L2Y})${RESET}"
tcup ${R1X} ${R1Y}; echo -n "${RED_FG}R(${R1X},${R1Y})${RESET}"
tcup 2 0;echo -n "MSG1 MSG2:${ST} ${L2X} > ${R1X} ${L2Y} > ${R1Y}"

STATE=$(box_coords_overlap MSG1 MSG3)
IFS=: read ST L2X R1X L2Y R1Y <<<${STATE}
tcup ${L2X} ${L2Y}; echo -n "${GREEN_FG}L(${L2X},${L2Y})${RESET}"
tcup ${R1X} ${R1Y}; echo -n "${RED_FG}R(${R1X},${R1Y})${RESET}"
tcup 3 0;echo -n "MSG1 MSG3:${ST} ${L2X} > ${R1X} ${L2Y} > ${R1Y}"

STATE=$(box_coords_overlap MSG3 MSG2)
IFS=: read ST L2X R1X L2Y R1Y <<<${STATE}
tcup ${L2X} ${L2Y}; echo -n "${GREEN_FG}L(${L2X},${L2Y})${RESET}"
tcup ${R1X} ${R1Y}; echo -n "${RED_FG}R(${R1X},${R1Y})${RESET}"
tcup 4 0;echo -n "MSG3 MSG2:${ST} ${L2X} > ${R1X} ${L2Y} > ${R1Y}"

STATE=$(box_coords_overlap MSG5 MSG2)
IFS=: read ST L2X R1X L2Y R1Y <<<${STATE}
tcup ${L2X} ${L2Y}; echo -n "${GREEN_FG}L(${L2X},${L2Y})${RESET}"
tcup ${R1X} ${R1Y}; echo -n "${RED_FG}R(${R1X},${R1Y})${RESET}"
tcup 5 0;echo -n "MSG5 MSG2:${ST} ${L2X} > ${R1X} ${L2Y} > ${R1Y}"

read
tput cnorm
