#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

#typeset -a TARGETS=(110 100 90 80 70 60 50 40 30 20 10 5)
typeset -a TARGETS=(84)
STR="Candace Owens - WHO Stood To Benefit From Charlie Kirk's Assassination? Candace EP 276"
for TGT in ${TARGETS};do
	S=$(clip ${STR} ${TGT})
	[[ ${#S} -gt ${TGT} ]] && echo "TGT:${TGT} ERROR" || echo ${TGT}:${#S}:${S}
done
