#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

_SCRIPT=${0:t}

usage () {
	echo "Usage: ${ITALIC}${WHITE_FG}source${RESET} ${_SCRIPT} on|off"
}

if [[ -z ${1} ]];then
	[[ -n ${ZSH_LIB_DIR} ]] && echo "LIB_TESTING is on" || echo "LIB_TESTING is off"
else
	if [[ ! ${1} =~ "on|off" ]];then
		echo "${RED_FG}Error${RESET}"
		usage
	elif [[ ${1} == 'on' ]];then
		export ZSH_LIB_DIR=${PWD}
		echo "LIB_TESTING is on"
	elif [[ ${1} == 'off' ]];then
		unset ZSH_LIB_DIR
		echo "LIB_TESTING is off"
	fi
fi
