#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"
PAGE=1
typeset -a _TARGETS=(3:3:1:next_target 4:4:1:seen 5:5:1:seen 9:9:1:seen 3:3:2:seem 4:4:2:seen 5:5:2:seen 9:9:2:seen)

echo ${_TARGETS}

echo ${_TARGETS[(r)*${1}:${PAGE}*]}
