#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

FDEPS=~/Code/LOCAL/find_lib_deps/find_lib_deps
_PFX=/usr/local/bin

typeset -a _LIB_APPS=(
${_PFX}/apps
${_PFX}/aux
${_PFX}/backup
${_PFX}/bt
${_PFX}/cfg
${_PFX}/chkupd
${_PFX}/cols
${_PFX}/desktop
${_PFX}/dut
${_PFX}/f
${_PFX}/fakebook
${_PFX}/fe
${_PFX}/find_music
${_PFX}/find_not_called
${_PFX}/flog
${_PFX}/fsub
${_PFX}/fut
${_PFX}/g
${_PFX}/gal
${_PFX}/genv
${_PFX}/ghis
${_PFX}/gsq
${_PFX}/gsub
${_PFX}/hist_no_dups
${_PFX}/icons
${_PFX}/installed
${_PFX}/irm
${_PFX}/jdraw
${_PFX}/kbd_shortcuts
${_PFX}/kill_idle_deluge
${_PFX}/lft
${_PFX}/listing
${_PFX}/loadstick
${_PFX}/lsc
${_PFX}/lsfuncs
${_PFX}/lst
${_PFX}/m3u
${_PFX}/make_standalone
${_PFX}/mkm3u
${_PFX}/mon
${_PFX}/myperms
${_PFX}/ntwk_disp
${_PFX}/nut
${_PFX}/o
${_PFX}/office
${_PFX}/pathabv
${_PFX}/perl_modules
${_PFX}/playit
${_PFX}/rb
${_PFX}/remind
${_PFX}/set_mp3_flac_tags
${_PFX}/shortcuts
${_PFX}/sut
${_PFX}/term_256_colors
${_PFX}/tip
${_PFX}/todo
${_PFX}/tut
${_PFX}/tvi
${_PFX}/tz
${_PFX}/vol
${_PFX}/vpn
${_PFX}/vut
${_PFX}/wless
${_PFX}/xut
${_PFX}/yt
${_PFX}/zopts
${_PFX}/zsh_sort_funcs
)

${FDEPS} ${_LIB_APPS}
