#!/usr/bin/zsh
#vim: syntax off
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

typeset -a LIST

RAWLIST=("${(f)$(find /usr/local/bin -maxdepth 1 -type f )}")
LIST+=(${RAWLIST})

RAWLIST=("${(f)$(find /usr/local/etc -maxdepth 1 -type f )}")
LIST+=(${RAWLIST})

LIST=$(for L in ${LIST};do
	echo ${L:h}:${L:t}
done | sort -t: -k2 | sed 's/:/\//g')

for L in ${LIST};do
	echo ${L}
done
