#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

# Imports
_LIB_DIR=${ZSH_LIB_DIR:=/usr/local/lib}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIST.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last
 
# Constants
_HIST_FILE=~/.zsh_history
_LAST_ACTION=/tmp/hist_action
_OBJ_TYPE="command"

typeset -A _HIST_KEYS=()
typeset -a _HIST_LIST=()

# Vars
_ALL=false
_HIST_LINES=46
_SEARCHTERM=''
_DELETE=false
_HIST_KEY=''
_SCRIPT=${0:t}
_ACTION_MSG=''

# Functions
action_do () {
	local M X
	local RC
	local NDX=0
	local HIT=false

	msg_box -t.5 "Removing ${#_MARKED} lines from history"

	for M in ${_MARKED};do
		list_set_selected ${M} ${_STALE_ROW}
		HIT=true
	done

	[[ ${HIT} == 'true' ]] && upd_history
}

action_warn () {
	local CNT=$(list_get_selected_count)
	local M 
	local -a DLIST
	local FN
	local HDRS=2
	
	msg_box "Working..."
	for M in ${_MARKED};do
		[[ ${_LOCAL_LIST[${M}]:h} == ${PWD} ]] && FN=${_LOCAL_LIST[${M}]:t} || FN=${_LOCAL_LIST[${M}]}
		DLIST+=${FN}
	done

	[[ -n ${_OFFSCREEN_ROWS_MSG} ]] && ((HDRS++))

	msg_box -O${RED_FG} -H${HDRS} -x10 -c -p -PD "<I><w>Please respond...<N>|$(str_pluralize ${OBJTYPE} ${CNT} true) queued for deletion|${_OFFSCREEN_ROWS_MSG}|$(msg_list_bullet ${(o)DLIST})"

	if [[ ${_MSG_KEY} == 'n' ]];then
		for M in ${_MARKED};do
			list_clear_selected ${M}
		done
	fi
}

item_decorate () {
	local NDX=${1}
	local _MAX=$(( _MAX_COLS - 10 ))

	case ${_LIST_SELECTED[${NDX}]} in
		2) echo -n "${E_STRIKE}${E_RED_FG}${_LIST[${NDX}]:gs/#/ /}${E_RESET} ${E_ITALIC}deleted${E_RESET}";;
		*) tput el;echo -n "${_LIST[${NDX}]:gs/#/ /}";;
	esac
}

collect_hist () {
	local SEARCHTERM=${1}
	local DATE TM CMD
	local NDX=0
	local D U
	local HL=$(cut -d' ' -f1 <<<$(wc -l ${_HIST_FILE}))

	fc -R
	while read DATE TM CMD;do
		((NDX++))
		printf "\rProcessing line ${WHITE_FG}%d${RESET} of ${WHITE_FG}%d${RESET} lines ${WHITE_FG}%%${BOLD}${GREEN_FG}%.2f${RESET}" ${NDX} ${HL} $(( NDX * 100. / ${HL} )) >&2
		[[ ${CMD} =~ "${_SCRIPT}$" ]] && continue
		if [[ -n ${_SEARCHTERM} ]];then
			[[ ! ${CMD} =~ ${_SEARCHTERM} ]] && continue
		fi
		D="${DATE} ${TM}"
		U=$(date -d ${D} +%s)
		echo "${U}#${D}#${CMD}" 
	done < <(fc -nrlt'%Y-%m-%d  %H:%M:%S' 1 100000) | sort -t'#' -k3 -u | sort -t'#' -k1 -r
}

upd_history () {
	local NDX=0
	local LINE
	local F1 F3 L

	cp ${_HIST_FILE} ${_HIST_FILE}.bak
	[[ -e ${_HIST_FILE}.new ]] && /bin/rm -f ${_HIST_FILE}.new

	[[ -n ${_SEARCHTERM} ]] && grep -av "${_SEARCHTERM}" < ${_HIST_FILE} > ${_HIST_FILE}.new

	NDX=0
	for L in ${(on)_LIST};do
		((NDX++))
		[[ -n ${_LIST_SELECTED[${NDX}]} ]] && continue
		IFS='#';read -r F1 F3 <<<$(cut -d# -f1,3 <<<${_LIST[${NDX}]});IFS=' '
		printf ": %s:0:%s\n" ${F1} "${F3}" >> ${_HIST_FILE}.new
	done

	mv -f ${_HIST_FILE}.new ${_HIST_FILE} # Replace history
}

#--Begin GetOpts--
local -a OPTIONS
local OPTION
local DESC

read -r -d '' DESC<<EOF
Display command line history
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTR
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTR+="-${OPTS[${O}]}"
	done
	echo ${OPTSTR}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		n) echo "<LINES>";;
		f) echo "<FILE>";;
	esac
}

usage () {
	local -a PENDING_MSGS=(${@})
	local OPTS=$(parse_opts ${OPTSTR})

	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	tabs 5
	(
	echo -e "\n${WHITE_FG}\nUsage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} [SEARCHTERM]\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug (repeats increase level)"
	echo -e "${WHITE_FG}-a${RESET} all history lines"
	echo -e "${WHITE_FG}-n${RESET} history lines (default: ${_HIST_LINES})"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"
	) >&2

	exit_leave $(err_msg_exit ${PENDING_MSGS})
}

OPTSTR=":HDan:"
OPTIND=0

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
	  a) _ALL=true;;
	  n) _HIST_LINES=${OPTARG};;
     :) print -u2 "${RED_FG}${_SCRIPT}${RESET}: option: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${RED_FG}${_SCRIPT}${RESET}: unknown option -${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $(( OPTIND - 1 ))
#--End GetOpts--

# Execution
[[ ${_DEBUG} -eq 0 ]] && do_smcup

[[ -n ${1} ]] && _SEARCHTERM=${1}

if ! validate_is_integer ${_HIST_LINES};then
	exit_leave $(err_msg_exit E "Option <-n> invalid - integer required")
fi

msg_box "<w>Collecting history...<N>"
_HIST_LIST=("${(f)$(collect_hist ${_SEARCHTERM})}")

# Set headings
list_set_header 'printf "Found:${WHITE_FG}%-d${RESET} $(str_pluralize ${_OBJ_TYPE} ${#_LIST}) Filter:${WHITE_FG}%s${RESET}  Selected:${WHITE_FG}%-d${RESET}  ${_PG}" ${#_LIST} "${_SEARCHTERM}" ${SELECTED_COUNT}'
list_add_header_break
list_set_header_break_color ${RED_FG}

# Set line item
list_set_line_item ' 
printf "${BOLD}${WHITE_FG}%4s${RESET}${_MARKER} ${SHADE}${BAR}%s${RESET}\n" ${_LIST_NDX} "$(item_decorate ${_LIST_NDX})"
'

list_set_select_action "delete"
list_set_action_msgs delete command
list_set_searchable true

while true;do
	# Display list
	list_select ${(on)_HIST_LIST}
	RC=${?}

	[[ ${RC} -eq 0 ]] && break

	# Get user selections
	_MARKED=($(list_get_selected))
	
	if [[ $(list_get_selected_count) -ne 0 ]];then
		action_warn
		if [[ ${_MSG_KEY} == "y" ]];then
			action_do
		fi
	fi
done

exit_leave
