#!/usr/bin/zsh
o /usr/share/icons/HighContrast/256x256/status/network-receive.png
o /home/kmiller/.local/share/Enpass/icons/item/web/onet.pl@2x.png
o /usr/share/icons/HighContrast/scalable/devices/network-wireless.svg
o /usr/share/icons/Yaru/256x256@2x/categories/preferences-system-network.png
o /usr/share/icons/Humanity/categories/64/applications-internet.svg


