#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

_EXT_DIR=/usr/local/etc
_TIP_DIR=${_EXT_DIR}/tips

find_keyword () {
	local -A OPTS=('-w' '-w' '-i' '-i')
	local -a GREP_OPTS=()
	local -a LIST
	local A F
	local HIT=false
	local KW=''

	for A in ${@};do
		GREP_OPTS+=${OPTS[${A}]}
	done
	KW=${@[-1]}

	LIST=("${(f)$(find ${_TIP_DIR} -type f ! -path ${_TIP_DIR})}")

	for F in ${LIST};do
		grep -q ${GREP_OPTS} ${KW} ${F}
		[[ ${?} -eq 0 ]] && HIT=true && echo "Keyword:\"${CYAN_FG}${KW}${RESET}\" located in:${WHITE_FG}${F}${RESET}"
	done

	[[ ${HIT} == 'false' ]] && echo "Keyword:\"${CYAN_FG}${KW}${RESET}\" not found"
}

find_keyword ${@}

