#!/usr/bin/zsh

# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"
  
typeset -a LOCAL_FILES

CONFIG_DIR=~/.config

if [[ ${1} == '-H' ]];then
	tabs 5
	echo "\n${WHITE_FG}Usage${RESET}:${0:t} [-H] [<dir>]"
	echo "${WHITE_FG} Desc${RESET}:Change to ~/.local/share directory\n"
	return
fi

[[ -z ${1} ]] && cd ${CONFIG_DIR}

if [[ -d ${CONFIG_DIR}/${1} ]];then
	cd ${CONFIG_DIR}/${1}
else
	echo "Non existant sub directory of ${CONFIG_DIR}:${WHITE_FG}${1}${RESET}"
	return
fi

