#!/usr/bin/zsh

#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"

typeset -a DEPS=()

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh ${DEPS}

# Constants
_TEMPLATE_DIR=/usr/local/etc/templates
_APP=${0:t}
_LIST=false

#--Begin GetOpts--
local -a OPTIONS
local OPTION
local DESC

read -r -d '' DESC<<EOF
Create application template
\tOptionally create a list application
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTR
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTR+="-${OPTS[${O}]}"
	done
	echo ${OPTSTR}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		a) echo "<APP_NAME>";;
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		t) echo "<FILE_TYPE>";;
	esac
}

usage () {
	local -a PENDING_MSGS=(${@})
	local OPTS=$(parse_opts ${OPTSTR})

	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	tabs 5
	(
	echo -e "\n${WHITE_FG}\nUsage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET} <APP_NAME>\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug (repeats increase level)"
	echo -e "${WHITE_FG}-l${RESET} create a list applications"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"
	) >&2

	[[ -n ${PENDING_MSGS} ]] && PENDING_MSGS=$(err_msg_exit "${PENDING_MSGS}")
	exit_leave ${PENDING_MSGS}
}

OPTSTR=":HDl"
OPTIND=0

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     l) _LIST=true;;
     :) print -u2 "${_SCRIPT_TAG} ${BOLD}${RED_FG}Option error${RESET}: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${_SCRIPT_TAG} ${BOLD}${RED_FG}Unknown option${RESET} - ${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $((OPTIND -1))
#--End GetOpts--

# Execution
[[ ${#} -ne 0 ]] && _APP_NAME=${1} || usage "Missing argument:$(opt_type a)"

if [[ -e ${_APP_NAME} ]];then
	echo -n "File:${WHITE_FG}${_APP_NAME}${RESET} exists. ${WHITE_FG}Overwrite${RESET}?"
	read -q RESPONSE
	[[ ${RESPONSE} != 'y' ]] && echo "\n${RED_FG}Operation cancelled" && exit || echo
fi

echo '#!/usr/bin/zsh' > ${_APP_NAME}
cat ${_TEMPLATE_DIR}/color.template.zsh >> ${_APP_NAME} && echo >>${_APP_NAME}
cat ${_TEMPLATE_DIR}/import.template.zsh >> ${_APP_NAME}
echo '\n# Declarations\n# Constants\n# Globals\n# Functions' >>${_APP_NAME}
echo >> ${_APP_NAME} && cat ${_TEMPLATE_DIR}/getopt.template.zsh >> ${_APP_NAME}
echo '\n# Execution' >>${_APP_NAME}

echo '\nexit_leave' >>${_APP_NAME}
chmod 775 ${_APP_NAME}

if [[ ${_LIST} == 'true' ]];then
	sed -i '/LIB_DEPS/i \
source ${_LIB_DIR}/LIST.zsh' ${_APP_NAME}

	sed -i "/Functions/ {
	r ${_TEMPLATE_DIR}/app_funcs.template.zsh
	}" ${_APP_NAME}

	sed -i "/Execution/ {
	r ${_TEMPLATE_DIR}/app_loop.template.zsh
	}" ${_APP_NAME}
fi

echo "Template for application:${WHITE_FG}${_APP_NAME}${RESET} created"
