#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLINK="\033[5m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

# Imports
[[ -z ${ZSH_LIB_DIR} ]] && _LIB_DIR=/usr/local/lib || _LIB_DIR=${ZSH_LIB_DIR}
source ${_LIB_DIR}/LIB_INIT.zsh # Must be first
source ${_LIB_DIR}/UTILS.zsh
source ${_LIB_DIR}/LIB_DEPS.zsh # Must be last

#--Begin GetOpts--
local -a OPTIONS
local OPTION
local DESC

read -r -d '' DESC<<EOF
Show 8bit foreground/background colors
EOF

parse_opts () {
	local OPTS=${@}
	local -a OPTSTR
	local LETTER_OPT
	local O

	for O in {1..${#OPTS}};do
		[[ ${OPTS[${O}]} =~ '[A-Za-z]' ]] && LETTER_OPT=${OPTS[${O}]}
		[[ ${O} -eq 1 && ${OPTS[${O}]} == ":" ]] && continue
		[[ ${O} -gt 1 && ${OPTS[${O}]} == ":" ]] && OPTSTR+=$(opt_type ${LETTER_OPT}) && continue
		OPTSTR+="-${OPTS[${O}]}"
	done
	echo ${OPTSTR}
}

opt_exists () {
	local OPT=${1}
	[[ $(( $OPTIONS[(Ie)${OPT}] )) -ne 0 ]] && return 0 || return 1
}

opt_type () {
	local OPT=${1}
	case ${OPT} in
		d) echo "<DIR>";;
		f) echo "<FILE>";;
		t) echo "<FILE_TYPE>";;
	esac
}

usage () {
	local -a PENDING_MSGS=(${@})
	local OPTS=$(parse_opts ${OPTSTR})

	[[ ${_SMCUP} == 'true' ]] && do_rmcup

	tabs 5
	(
	echo -e "\n${WHITE_FG}\nUsage${RESET}: ${_SCRIPT} ${WHITE_FG}[${RESET}${OPTS}${WHITE_FG}]${RESET}\n"
	echo -e "${WHITE_FG}-H${RESET} help"
	echo -e "${WHITE_FG}-D${RESET} debug (repeats increase level)"
	echo -e "${WHITE_FG}-h${RESET} block height"
	echo -e "${WHITE_FG}-w${RESET} block width"
	echo -e "${WHITE_FG}-e${RESET} block edge"
	echo -e "${WHITE_FG}-s${RESET} block separation"
	echo -e "\n${WHITE_FG}DESC${RESET}:${DESC}"
	) >&2

	exit_leave $(err_msg_exit "${PENDING_MSGS}")
}

OPTSTR=":HDh:w:e:s:"
OPTIND=0

HEIGHT=3
WIDTH=18
EDGE=150
SEP=4

while getopts ${OPTSTR} OPTION;do
	case $OPTION in
     H) usage;;
     D) dbg_set_level;;
     h) HEIGHT=${OPTARG};;
     w) WIDTH=${OPTARG};;
     e) EDGE=${OPTARG};;
     s) SEP=${OPTARG};;
     :) print -u2 "${_SCRIPT_TAG} ${BOLD}${RED_FG}Option error${RESET}: -${OPTARG} requires an argument"; usage;;
    \?) print -u2 "${_SCRIPT_TAG} ${BOLD}${RED_FG}Unknown option${RESET} - ${OPTARG}"; usage;;
	esac
	[[ ${OPTION} != 'D' ]] && OPTIONS+=${OPTION}
done
shift $(( OPTIND -1 ))
#--End GetOpts--

# Execution
do_smcup
echo "${CSR_OFF}"
clear
tput cup 0 0;
ROW_START=0
ROW=0
COL=0
MODE=FG
G=38
for C in {1..255};do
	tput cup $((ROW_START+ROW)) ${COL}
	tput ech 20
	echo "\033[${G};5;${C}mTEXT ${MODE} COLOR:${WHITE_FG}${C}${RESET}"
	((ROW++))
	[[ $((ROW % ${HEIGHT})) -eq 0 ]] && { ((COL+=${WIDTH})) && ROW=0 }
	[[ ${COL} -gt ${EDGE} ]] && { COL=0 && ((ROW_START+=${SEP})) }
done
echo -n "Press any key for BG";read

clear
tput cup 0 0;
ROW_START=0
ROW=0
COL=0
MODE=BG
G=48
for C in {1..255};do
	tput cup $((ROW_START+ROW)) ${COL}
	tput ech 20
	echo "\033[${G};5;${C}mTEXT ${MODE} COLOR:${WHITE_FG}${C}${RESET}"
	((ROW++))
	[[ $((ROW % ${HEIGHT})) -eq 0 ]] && { ((COL+=${WIDTH})) && ROW=0 }
	[[ ${COL} -gt ${EDGE} ]] && { COL=0 && ((ROW_START+=${SEP})) }
done
read
echo "${CSR_ON}"

exit_leave
