#!/usr/bin/zsh
# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"
BLINK="\033[5m"
BLACK_BG="\033[40m"
BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"
CSR_OFF="\033[?25l"
CSR_ON="\033[?25h"

clear
tput cup 0 0;
ROW_START=0
ROW=0
COL=0
MODE=FG
G=38
for C in {1..255};do
	tput cup $((ROW_START+ROW)) ${COL}
	tput ech 20
	echo "\033[${G};5;${C}mTEXT ${MODE} COLOR:${WHITE_FG}${C}${RESET}"
	((ROW++))
	[[ $((ROW % 15)) -eq 0 ]] && { ((COL+=18)) && ROW=0 }
	[[ ${COL} -gt 150 ]] && { COL=0 && ((ROW_START+=16)) }
done
read

clear
tput cup 0 0;
ROW_START=0
ROW=0
COL=0
MODE=BG
G=48
for C in {1..255};do
	tput cup $((ROW_START+ROW)) ${COL}
	tput ech 20
	echo "\033[${G};5;${C}mTEXT ${MODE} COLOR:${WHITE_FG}${C}${RESET}"
	((ROW++))
	[[ $((ROW % 15)) -eq 0 ]] && { ((COL+=18)) && ROW=0 }
	[[ ${COL} -gt 150 ]] && { COL=0 && ((ROW_START+=16)) }
done
read
