#!/usr/bin/zsh
#Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

COMPLETED=~/Downloads/Torrents/Completed
( rm -f ${COMPLETED}/* ) >/dev/null 2>&1

NDX=0
while true;do
	((NDX++))
	touch ${COMPLETED}/"VIDEO${NDX}.1997.s01e01.1080p.a.bunch.of.extraneous.stuff.mkv"
	sleep 1
	[[ ${NDX} -gt 2 ]] && break
done
