#!/usr/bin/zsh

# Inline ansi
BOLD="\033[1m"
ITALIC="\033[3m"
RESET="\033[m"
REVERSE="\033[7m"
STRIKE="\033[9m"
UNDER="\033[4m"

BLACK_BG="\033[40m"

BLUE_FG="\033[34m"
CYAN_FG="\033[36m"
GREEN_FG="\033[32m"
MAGENTA_FG="\033[35m"
RED_FG="\033[31m"
WHITE_FG="\033[37m"
YELLOW_FG="\033[33m"

WHITE_ON_GREY="\033[0m\033[0;1;37;100m"
  
# Declarations
typeset -a _LOCAL_FILES
typeset -a _PROD_DIRS=(/usr/local/bin /usr/local/lib ${HOME}/.local/bin ${HOME}/.local/share)

# Constants
_CODEBASE=~/Code
_LOCAL=${_CODEBASE}/LOCAL
_LANG=${_CODEBASE}/LANG
_PYPROJ=${_LANG}/Python/PROJECTS

# Functions
get_prod () {
	local FN=${1}
	local EXELIST=("${(f)$(fut findexe ${FN:t})}")
	local F D
	local FX DX

	for F in ${EXELIST};do
		FX=$(tr '/' '_' <<<${F})
		for D in ${_PROD_DIRS};do
			DX=$(tr '/' '_' <<<${D})
			if grep -q ${DX} <<<${FX};then
				echo ${F}
				return
			fi
		done
	done
}

# Usage
if [[ ${1} == '-H' ]];then
	tabs 5
	echo "\n${WHITE_FG}Usage${RESET}:${0:t} [-H] [<dir>]"
	echo "${WHITE_FG} Desc${RESET}:Change to development directory\n"
	echo "Directories searched:\n"
	echo "${_CODEBASE}"
	echo "${_LOCAL}"
	echo "${_LANG}"
	echo "${_PYPROJ}"
	echo
	return
fi

# Execution
[[ -z ${1} ]] && cd ${_CODEBASE}

if [[ -d ${_LOCAL}/${1} ]];then
	cd ${_LOCAL}/${1} 
elif [[ -d ${_LOCAL}/${(U)1} ]];then
	cd ${_LOCAL}/${(U)1} 
elif [[ -d ${_LANG}/${1} ]];then
	cd ${_LANG}/${1} 
elif [[ -d ${_LANG}/${(U)1} ]];then
	cd ${_LANG}/${(U)1} 
elif [[ -d ${_CODEBASE}/${1} ]];then
	cd ${_CODEBASE}/${1} 
elif [[ -d ${_CODEBASE}/${(U)1} ]];then
	cd ${_CODEBASE}/${(U)1} 
elif [[ -d ${_PYPROJ}/${1} ]];then
	cd ${_PYPROJ}/${1} 
	[[ -d venv ]] && cd venv
elif [[ -d ${_PYPROJ}/${(U)1} ]];then
	cd ${_PYPROJ}/${(U)1} 
	[[ -d venv ]] && cd venv
else
	echo "No development directory found:${WHITE_FG}${1}${RESET}"
	return
fi

_LOCAL_FILES=()
{
	LONGEST=0
	for F in ${PWD}/*;do
		[[ ${F:e} == 'bak' ]] && continue
		if [[ $(file ${F}) =~ 'zsh script' || ${F:e} == 'zsh' || ${F:e} == 'js' ]];then
			_LOCAL_FILES+=${F}
			[[ ${#F} -gt ${LONGEST} ]] && LONGEST=${#F}
		fi
	done
} >/dev/null 2>&1


if [[ -n ${_LOCAL_FILES} ]];then
	for F in ${_LOCAL_FILES};do
		PROD=$(get_prod ${F})
		if [[ -n ${PROD} ]];then
			diff -b ${F} ${PROD} >/dev/null 2>&1
			if [[ ${?} -ne 0 ]];then
				printf "Development:${WHITE_FG}%*s${RESET} ${BOLD}${RED_FG}%-15s${RESET} Production:${WHITE_FG}%s${RESET}\n" ${LONGEST} ${F}   'does not match' ${PROD}
			else
				printf "Development:${WHITE_FG}%*s${RESET} ${BOLD}${GREEN_FG}%-15s${RESET} Production:${WHITE_FG}%s${RESET}\n" ${LONGEST} ${F} '       matches' ${PROD}
			fi
		fi
	done
fi
